import { NextRequest, NextResponse } from "next/server";
import { enterpriseAccess } from "@/lib/enterprise/access";
import { verifyAuditChain } from "@/lib/enterprise/audit";
import { ENTERPRISE_GRAPHQL_SCHEMA, validGraphqlRequest } from "@/lib/enterprise/graphql";
import { getEnterpriseStore } from "@/lib/enterprise/store";
import type { EnterpriseResourceKind } from "@/lib/enterprise/types";
import { RESOURCE_PERMISSION, sanitizeResource } from "@/lib/enterprise/validation";
import { readLimitedJson } from "@/lib/http/body";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
const response = (data: unknown, status = 200) => NextResponse.json(data, { status, headers: { "cache-control": "no-store" } });
export async function GET() { return new NextResponse(ENTERPRISE_GRAPHQL_SCHEMA, { headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "public, max-age=3600" } }); }
export async function POST(req: NextRequest) { try { const { operationName, variables } = validGraphqlRequest(await readLimitedJson(req, 50_000)), orgId = typeof variables.orgId === "string" ? variables.orgId : null, store = await getEnterpriseStore(); if (operationName === "EnterpriseOverview") { const access = await enterpriseAccess(req, "enterprise:read", orgId); if (!access) return response({ errors: [{ message: "Forbidden", extensions: { code: "FORBIDDEN" } }] }, 403); return response({ data: { enterpriseOverview: await store.overview(access.workspace.id) } }); } if (operationName === "EnterpriseAudit") { const access = await enterpriseAccess(req, "audit:read", orgId); if (!access) return response({ errors: [{ message: "Forbidden", extensions: { code: "FORBIDDEN" } }] }, 403); const items = await store.auditEvents(access.workspace.id, Math.min(1000, Math.max(1, Number(variables.first ?? 100))), typeof variables.afterSequence === "string" ? variables.afterSequence : undefined); return response({ data: { enterpriseAudit: { items, integrity: items[0]?.sequence === "1" ? verifyAuditChain(items) : { valid: null, reason: "Partial page; use audit export for full-chain verification." } } } }); } if (operationName === "EnterpriseResources") { const kind = variables.kind as EnterpriseResourceKind, permission = RESOURCE_PERMISSION[kind]; if (!permission) throw new Error("Unknown enterprise resource kind."); const access = await enterpriseAccess(req, permission, orgId); if (!access) return response({ errors: [{ message: "Forbidden", extensions: { code: "FORBIDDEN" } }] }, 403); const items = await store.list(access.workspace.id, kind, { limit: Math.min(200, Math.max(1, Number(variables.first ?? 100))), afterId: typeof variables.after === "string" ? variables.after : undefined }); return response({ data: { enterpriseResources: { items: ["apiTokens", "identityProviders", "integrations"].includes(kind) ? items.map(({ secretHash: _hash, scimTokenHash: _scim, configEncrypted: _config, ...item }) => item) : items } } }); } const kind = operationName === "RequestApproval" ? "approvals" : "exceptions", permission = RESOURCE_PERMISSION[kind], access = await enterpriseAccess(req, permission, orgId); if (!access) return response({ errors: [{ message: "Forbidden", extensions: { code: "FORBIDDEN" } }] }, 403); const input = sanitizeResource(kind, variables.input, access.actorId), item = await store.createAudited(access.workspace.id, kind, input as never, { actorType: access.actorType, actorId: access.actorId, action: `enterprise.graphql.${kind}.created`, resourceType: kind, requestId: req.headers.get("x-request-id"), ipHash: null, detail: {} }); return response({ data: { [operationName === "RequestApproval" ? "requestApproval" : "requestRiskException"]: item } }); } catch (error) { return response({ errors: [{ message: (error as Error).message, extensions: { code: "BAD_USER_INPUT" } }] }, 400); } }
