import type { AgencyStore } from "./store-model";

export async function agencyAnalytics(store: AgencyStore, agencyId: string, days = 30) {
  const [workspace, clients, members, jobs, reports, activity, allWorkspaces] = await Promise.all([store.workspace(agencyId), store.clients(agencyId), store.memberships(agencyId), store.jobs(agencyId, 200), store.reports(agencyId, 200), store.activity(agencyId, 200), store.allWorkspaces()]);
  if (!workspace) throw new Error("Agency workspace not found"); const start = new Date(); start.setUTCDate(start.getUTCDate() - Math.max(7, Math.min(days, 365)) + 1); start.setUTCHours(0, 0, 0, 0);
  const series = Array.from({ length: Math.max(7, Math.min(days, 365)) }, (_, index) => { const date = new Date(start); date.setUTCDate(start.getUTCDate() + index); const key = date.toISOString().slice(0, 10); return { date: key, scans: 0, reports: 0, api: 0, changes: 0 }; }); const byDate = new Map(series.map((item) => [item.date, item]));
  for (const job of jobs) { const point = byDate.get(job.createdAt.slice(0, 10)); if (point) job.type === "scan" ? point.scans += job.clientOrgIds.length : point.reports += job.clientOrgIds.length; }
  for (const item of activity) { const point = byDate.get(item.createdAt.slice(0, 10)); if (!point) continue; if (item.actorId.startsWith("api-key:")) point.api += 1; if (item.type.includes("finding") || item.type.includes("client") || item.type.includes("bulk")) point.changes += 1; }
  const revenueByCurrency = clients.reduce<Record<string, number>>((totals, client) => { if (client.monthlyPriceCents) totals[client.currency] = (totals[client.currency] ?? 0) + client.monthlyPriceCents; return totals; }, {});
  const children = allWorkspaces.filter((item) => item.resellerParentId === agencyId); const parent = workspace.resellerParentId ? allWorkspaces.find((item) => item.id === workspace.resellerParentId) ?? null : null;
  const resellerChildren = await Promise.all(children.map(async (item) => { const managed = await store.clients(item.id); return { id: item.id, name: item.name, clients: managed.length, revenueByCurrency: managed.reduce<Record<string, number>>((totals, client) => { if (client.monthlyPriceCents) totals[client.currency] = (totals[client.currency] ?? 0) + client.monthlyPriceCents; return totals; }, {}) }; }));
  return { periodDays: series.length, series, utilization: { activeClients: clients.filter((client) => client.status === "active").length, totalClients: clients.length, activeSeats: members.filter((member) => member.active).length, pendingJobs: jobs.filter((job) => job.status === "queued").length, reports: reports.filter((report) => new Date(report.createdAt) >= start).length, apiCalls: activity.filter((item) => item.actorId.startsWith("api-key:") && new Date(item.createdAt) >= start).length }, billing: { revenueByCurrency, clientCountByMode: clients.reduce<Record<string, number>>((totals, client) => ({ ...totals, [client.billingMode]: (totals[client.billingMode] ?? 0) + 1 }), {}), clients: clients.map((client) => ({ id: client.id, name: client.organizationName, mode: client.billingMode, monthlyPriceCents: client.monthlyPriceCents, currency: client.currency, serviceTier: client.serviceTier })) }, reseller: { parent: parent ? { id: parent.id, name: parent.name } : null, children: resellerChildren } };
}
