import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/db/prisma";
import type { AgencyStore } from "./store-model";
import type { AgencyActivity, AgencyApiKey, AgencyBulkJob, AgencyClient, AgencyFindingShare, AgencyGroup, AgencyInvite, AgencyMembership, AgencyNote, AgencyReport, AgencyRole, AgencySlaEvent, AgencyWorkspace } from "./types";

type WorkspaceRow={id:string;ownerOrgId:string;name:string;slug:string;whiteLabel:boolean;consultantMode:boolean;logoUrl:string|null;primaryColor:string;accentColor:string;supportEmail:string|null;customDomain:string|null;emailFromName:string|null;emailFooter:string|null;resellerParentId:string|null;createdAt:Date;updatedAt:Date};
type MemberRow={agencyId:string;userId:string;role:string;seatLabel:string|null;active:boolean;createdAt:Date};
type ClientRow={id:string;agencyId:string;orgId:string;organizationName:string;organizationSlug:string;groupId:string|null;status:string;portalMode:string;externalRef:string|null;serviceTier:string;slaResponseMinutes:number;notificationRouting:unknown;billingMode:string;monthlyPriceCents:number|null;currency:string;addedAt:Date;offboardedAt:Date|null};
type GroupRow={id:string;agencyId:string;name:string;color:string;description:string|null;createdAt:Date};
type NoteRow={id:string;agencyId:string;clientId:string;authorId:string;body:string;visibility:string;createdAt:Date;updatedAt:Date};
type ShareRow={id:string;agencyId:string;clientId:string;recommendationId:string;sharedBy:string;clientMessage:string|null;status:string;sharedAt:Date};
type JobRow={id:string;agencyId:string;type:string;status:string;idempotencyKey:string;clientOrgIds:string[];payload:unknown;result:unknown;createdBy:string;createdAt:Date};
type ActivityRow={id:string;agencyId:string;clientOrgId:string|null;actorId:string;type:string;message:string;detail:unknown;createdAt:Date};
type KeyRow={id:string;agencyId:string;name:string;prefix:string;scopes:string[];createdBy:string;createdAt:Date;lastUsedAt:Date|null;expiresAt:Date|null;revokedAt:Date|null};
type InviteRow={id:string;agencyId:string;email:string;role:string;kind:string;clientId:string|null;createdBy:string;createdAt:Date;expiresAt:Date;acceptedAt:Date|null;acceptedBy:string|null;revokedAt:Date|null};
type ReportRow={id:string;agencyId:string;clientOrgId:string|null;periodStart:Date;periodEnd:Date;kind:string;status:string;title:string;content:unknown;branding:unknown;createdBy:string;createdAt:Date};
type SlaRow={id:string;clientId:string;findingId:string;priority:string;openedAt:Date;dueAt:Date;resolvedAt:Date|null;breached:boolean;status:string;acknowledgedAt:Date|null;acknowledgedBy:string|null;lastObservedAt:Date;escalatedAt:Date|null};
const uid=(prefix:string)=>`${prefix}_${randomUUID()}`;
const uniqueViolation=(error:unknown)=>{const value=error as{code?:string;meta?:{code?:string}};return value.code==="P2010"&&value.meta?.code==="23505";};
const object=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
const mapWorkspace=(r:WorkspaceRow):AgencyWorkspace=>({id:r.id,ownerOrgId:r.ownerOrgId,name:r.name,slug:r.slug,consultantMode:r.consultantMode,resellerParentId:r.resellerParentId,branding:{whiteLabel:r.whiteLabel,logoUrl:r.logoUrl,primaryColor:r.primaryColor,accentColor:r.accentColor,supportEmail:r.supportEmail,customDomain:r.customDomain,emailFromName:r.emailFromName,emailFooter:r.emailFooter},createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()});
const mapMember=(r:MemberRow):AgencyMembership=>({...r,role:r.role as AgencyRole,createdAt:r.createdAt.toISOString()});
const mapClient=(r:ClientRow):AgencyClient=>({...r,status:r.status as AgencyClient["status"],portalMode:r.portalMode as AgencyClient["portalMode"],notificationRouting:object(r.notificationRouting),addedAt:r.addedAt.toISOString(),offboardedAt:r.offboardedAt?.toISOString()??null});
const mapJob=(r:JobRow):AgencyBulkJob=>({...r,type:r.type as AgencyBulkJob["type"],payload:object(r.payload),createdAt:r.createdAt.toISOString()});
const mapInvite=(r:InviteRow):AgencyInvite=>({...r,role:r.role as AgencyRole,kind:r.kind as AgencyInvite["kind"],createdAt:r.createdAt.toISOString(),expiresAt:r.expiresAt.toISOString(),acceptedAt:r.acceptedAt?.toISOString()??null,revokedAt:r.revokedAt?.toISOString()??null});
const mapSla=(r:SlaRow):AgencySlaEvent=>({...r,priority:r.priority as AgencySlaEvent["priority"],status:r.status as AgencySlaEvent["status"],openedAt:r.openedAt.toISOString(),dueAt:r.dueAt.toISOString(),resolvedAt:r.resolvedAt?.toISOString()??null,acknowledgedAt:r.acknowledgedAt?.toISOString()??null,lastObservedAt:r.lastObservedAt.toISOString(),escalatedAt:r.escalatedAt?.toISOString()??null});
const mapReport=(r:ReportRow):AgencyReport=>({id:r.id,agencyId:r.agencyId,clientOrgId:r.clientOrgId,periodStart:r.periodStart.toISOString(),periodEnd:r.periodEnd.toISOString(),kind:r.kind as AgencyReport["kind"],status:r.status,title:r.title,content:object(r.content),branding:{whiteLabel:Boolean(object(r.branding).whiteLabel),logoUrl:object(r.branding).logoUrl as string|null,primaryColor:String(object(r.branding).primaryColor??"#38e1c3"),accentColor:String(object(r.branding).accentColor??"#5b8cff"),supportEmail:object(r.branding).supportEmail as string|null,customDomain:object(r.branding).customDomain as string|null,emailFromName:object(r.branding).emailFromName as string|null,emailFooter:object(r.branding).emailFooter as string|null},createdBy:r.createdBy,createdAt:r.createdAt.toISOString()});
const clientSelect=`SELECT c.*, o.name AS "organizationName", o.slug AS "organizationSlug" FROM agency_clients c JOIN organizations o ON o.id=c."orgId"`;

export class PrismaAgencyStore implements AgencyStore{
 readonly durable=true;
 async workspaceForUser(userId:string){const rows=await prisma.$queryRaw<WorkspaceRow[]>`SELECT w.* FROM agency_workspaces w JOIN agency_memberships m ON m."agencyId"=w.id WHERE m."userId"=${userId} AND m.active=true ORDER BY m."createdAt" ASC LIMIT 1`;if(!rows[0])return null;const member=await this.membershipForUser(rows[0].id,userId);return member?{workspace:mapWorkspace(rows[0]),membership:member}:null;}
 async workspacesForUser(userId:string){const rows=await prisma.$queryRaw<WorkspaceRow[]>`SELECT w.* FROM agency_workspaces w JOIN agency_memberships m ON m."agencyId"=w.id WHERE m."userId"=${userId} AND m.active=true ORDER BY w.name`;const memberships=await Promise.all(rows.map(row=>this.membershipForUser(row.id,userId)));return rows.flatMap((row,index)=>memberships[index]?[{workspace:mapWorkspace(row),membership:memberships[index]!}]:[]);}
 async workspaceByCustomDomain(domain:string){const normalized=domain.trim().toLowerCase().replace(/:\d+$/,"");const rows=await prisma.$queryRaw<WorkspaceRow[]>`SELECT * FROM agency_workspaces WHERE lower("customDomain")=${normalized} LIMIT 1`;return rows[0]?mapWorkspace(rows[0]):null;}
 async membershipForUser(agencyId:string,userId:string){const rows=await prisma.$queryRaw<MemberRow[]>`SELECT * FROM agency_memberships WHERE "agencyId"=${agencyId} AND "userId"=${userId} AND active=true LIMIT 1`;return rows[0]?mapMember(rows[0]):null;}
 async workspace(id:string){const rows=await prisma.$queryRaw<WorkspaceRow[]>`SELECT * FROM agency_workspaces WHERE id=${id} LIMIT 1`;return rows[0]?mapWorkspace(rows[0]):null;}
 async allWorkspaces(){return(await prisma.$queryRaw<WorkspaceRow[]>`SELECT * FROM agency_workspaces ORDER BY name`).map(mapWorkspace);}
 async createWorkspace(input:{ownerOrgId:string;ownerUserId:string;name:string;slug:string}){const agencyId=uid("agency"),now=new Date();await prisma.$transaction(async tx=>{await tx.$executeRaw`INSERT INTO agency_workspaces (id,"ownerOrgId",name,slug,"createdAt","updatedAt") VALUES (${agencyId},${input.ownerOrgId},${input.name},${input.slug},${now},${now})`;await tx.$executeRaw`INSERT INTO agency_memberships ("agencyId","userId",role,"seatLabel",active,"createdAt") VALUES (${agencyId},${input.ownerUserId},CAST('owner' AS "AgencyRole"),'Principal',true,${now})`;});return (await this.workspace(agencyId))!;}
 async updateWorkspace(id:string,patch:Partial<Pick<AgencyWorkspace,"name"|"consultantMode"|"resellerParentId">>&{branding?:Partial<AgencyWorkspace["branding"]>}){const current=await this.workspace(id);if(!current)return null;const b={...current.branding,...patch.branding};await prisma.$executeRaw`UPDATE agency_workspaces SET name=${patch.name??current.name},"consultantMode"=${patch.consultantMode??current.consultantMode},"resellerParentId"=${patch.resellerParentId===undefined?current.resellerParentId:patch.resellerParentId},"whiteLabel"=${b.whiteLabel},"logoUrl"=${b.logoUrl},"primaryColor"=${b.primaryColor},"accentColor"=${b.accentColor},"supportEmail"=${b.supportEmail},"customDomain"=${b.customDomain},"emailFromName"=${b.emailFromName},"emailFooter"=${b.emailFooter},"updatedAt"=${new Date()} WHERE id=${id}`;return this.workspace(id);}
 async memberships(agencyId:string){return(await prisma.$queryRaw<MemberRow[]>`SELECT * FROM agency_memberships WHERE "agencyId"=${agencyId} ORDER BY "createdAt"`).map(mapMember);}
 async upsertMembership(input:{agencyId:string;userId:string;role:AgencyRole;seatLabel?:string|null}){await prisma.$executeRaw`INSERT INTO agency_memberships ("agencyId","userId",role,"seatLabel",active,"createdAt") VALUES (${input.agencyId},${input.userId},CAST(${input.role} AS "AgencyRole"),${input.seatLabel??null},true,${new Date()}) ON CONFLICT ("agencyId","userId") DO UPDATE SET role=EXCLUDED.role,"seatLabel"=COALESCE(EXCLUDED."seatLabel",agency_memberships."seatLabel"),active=true`;return(await this.membershipForUser(input.agencyId,input.userId))!;}
 async updateMembership(agencyId:string,userId:string,patch:{role?:AgencyRole;active?:boolean;seatLabel?:string|null}){const current=(await this.memberships(agencyId)).find(x=>x.userId===userId);if(!current)return null;await prisma.$executeRaw`UPDATE agency_memberships SET role=CAST(${patch.role??current.role} AS "AgencyRole"),active=${patch.active??current.active},"seatLabel"=${patch.seatLabel===undefined?current.seatLabel:patch.seatLabel} WHERE "agencyId"=${agencyId} AND "userId"=${userId}`;return(await this.memberships(agencyId)).find(x=>x.userId===userId)??null;}
 async clients(agencyId:string){return(await prisma.$queryRawUnsafe<ClientRow[]>(`${clientSelect} WHERE c."agencyId"=$1 AND c.status<>'offboarded' ORDER BY c."addedAt" DESC`,agencyId)).map(mapClient);}
 async addClient(input:{agencyId:string;orgId:string;organizationName:string;organizationSlug:string;groupId?:string|null;externalRef?:string|null}){const id=uid("client");try{await prisma.$executeRaw`INSERT INTO agency_clients (id,"agencyId","orgId","groupId","externalRef") VALUES (${id},${input.agencyId},${input.orgId},${input.groupId??null},${input.externalRef??null})`;}catch(e){if(uniqueViolation(e))return null;throw e;}const rows=await prisma.$queryRawUnsafe<ClientRow[]>(`${clientSelect} WHERE c.id=$1`,id);return rows[0]?mapClient(rows[0]):null;}
 async updateClient(agencyId:string,clientId:string,patch:Partial<AgencyClient>){const current=(await this.clients(agencyId)).find(x=>x.id===clientId);if(!current)return null;const next={...current,...patch};await prisma.$executeRaw`UPDATE agency_clients SET "groupId"=${next.groupId},status=CAST(${next.status} AS "AgencyClientStatus"),"portalMode"=CAST(${next.portalMode} AS "AgencyPortalMode"),"externalRef"=${next.externalRef},"serviceTier"=${next.serviceTier},"slaResponseMinutes"=${Math.max(15,Math.min(43200,next.slaResponseMinutes))},"notificationRouting"=CAST(${JSON.stringify(next.notificationRouting)} AS jsonb),"billingMode"=${next.billingMode},"monthlyPriceCents"=${next.monthlyPriceCents},currency=${next.currency},"offboardedAt"=${next.status==="offboarded"?new Date():null} WHERE id=${clientId} AND "agencyId"=${agencyId}`;const rows=await prisma.$queryRawUnsafe<ClientRow[]>(`${clientSelect} WHERE c.id=$1`,clientId);return rows[0]?mapClient(rows[0]):null;}
 async groups(agencyId:string){return(await prisma.$queryRaw<GroupRow[]>`SELECT * FROM agency_groups WHERE "agencyId"=${agencyId} ORDER BY name`).map(r=>({...r,createdAt:r.createdAt.toISOString()}));}
 async createGroup(input:{agencyId:string;name:string;color:string;description?:string|null}){const id=uid("group");try{await prisma.$executeRaw`INSERT INTO agency_groups (id,"agencyId",name,color,description) VALUES (${id},${input.agencyId},${input.name},${input.color},${input.description??null})`;}catch(e){if(uniqueViolation(e))return null;throw e;}return(await this.groups(input.agencyId)).find(x=>x.id===id)??null;}
 async notes(agencyId:string,clientId:string){return(await prisma.$queryRaw<NoteRow[]>`SELECT * FROM agency_notes WHERE "agencyId"=${agencyId} AND "clientId"=${clientId} ORDER BY "createdAt" DESC`).map(r=>({...r,visibility:r.visibility as AgencyNote["visibility"],createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()}));}
 async createNote(input:{agencyId:string;clientId:string;authorId:string;body:string;visibility:"internal"|"shared"}){const id=uid("note"),now=new Date();await prisma.$executeRaw`INSERT INTO agency_notes (id,"agencyId","clientId","authorId",body,visibility,"createdAt","updatedAt") VALUES (${id},${input.agencyId},${input.clientId},${input.authorId},${input.body},${input.visibility},${now},${now})`;return(await this.notes(input.agencyId,input.clientId)).find(x=>x.id===id)!;}
 async shareFinding(input:{agencyId:string;clientId:string;recommendationId:string;sharedBy:string;clientMessage?:string|null}){const id=uid("share"),now=new Date();await prisma.$executeRaw`INSERT INTO agency_finding_shares (id,"agencyId","clientId","recommendationId","sharedBy","clientMessage",status,"sharedAt") VALUES (${id},${input.agencyId},${input.clientId},${input.recommendationId},${input.sharedBy},${input.clientMessage??null},'shared',${now}) ON CONFLICT ("agencyId","clientId","recommendationId") DO UPDATE SET "sharedBy"=EXCLUDED."sharedBy","clientMessage"=EXCLUDED."clientMessage",status='shared',"sharedAt"=EXCLUDED."sharedAt"`;return(await this.findingShares(input.agencyId,input.clientId)).find(x=>x.recommendationId===input.recommendationId)!;}
 async findingShares(agencyId:string,clientId:string){return(await prisma.$queryRaw<ShareRow[]>`SELECT * FROM agency_finding_shares WHERE "agencyId"=${agencyId} AND "clientId"=${clientId} AND status='shared' ORDER BY "sharedAt" DESC`).map(r=>({...r,sharedAt:r.sharedAt.toISOString()}));}
 async createJob(input:{agencyId:string;type:"scan"|"report"|"digest";idempotencyKey:string;clientOrgIds:string[];payload:Record<string,unknown>;createdBy:string}){const existing=await prisma.$queryRaw<JobRow[]>`SELECT * FROM agency_bulk_jobs WHERE "idempotencyKey"=${input.idempotencyKey} LIMIT 1`;if(existing[0])return mapJob(existing[0]);const id=uid("job");try{await prisma.$executeRaw`INSERT INTO agency_bulk_jobs (id,"agencyId",type,"idempotencyKey","clientOrgIds",payload,"createdBy") VALUES (${id},${input.agencyId},${input.type},${input.idempotencyKey},${input.clientOrgIds},CAST(${JSON.stringify(input.payload)} AS jsonb),${input.createdBy})`;}catch(error){if(!uniqueViolation(error))throw error;}const row=(await prisma.$queryRaw<JobRow[]>`SELECT * FROM agency_bulk_jobs WHERE "idempotencyKey"=${input.idempotencyKey} LIMIT 1`)[0];if(!row)throw new Error("Idempotent agency job could not be resolved");return mapJob(row);}
 async jobs(agencyId:string,limit=50){return(await prisma.$queryRaw<JobRow[]>`SELECT * FROM agency_bulk_jobs WHERE "agencyId"=${agencyId} ORDER BY "createdAt" DESC LIMIT ${Math.min(limit,200)}`).map(mapJob);}
 async finishJob(agencyId:string,id:string,status:"completed"|"partially_failed"|"failed",result:unknown){await prisma.$executeRaw`UPDATE agency_bulk_jobs SET status=CAST(${status} AS "AgencyJobStatus"),result=CAST(${JSON.stringify(result)} AS jsonb),"completedAt"=${new Date()} WHERE id=${id} AND "agencyId"=${agencyId}`;return(await this.jobs(agencyId,200)).find(x=>x.id===id)??null;}
 async appendActivity(input:Omit<AgencyActivity,"id"|"createdAt">){const id=uid("activity"),now=new Date();await prisma.$executeRaw`INSERT INTO agency_activity (id,"agencyId","clientOrgId","actorId",type,message,detail,"createdAt") VALUES (${id},${input.agencyId},${input.clientOrgId},${input.actorId},${input.type},${input.message},CAST(${JSON.stringify(input.detail)} AS jsonb),${now})`;return{id,...input,createdAt:now.toISOString()};}
 async activity(agencyId:string,limit=100){return(await prisma.$queryRaw<ActivityRow[]>`SELECT * FROM agency_activity WHERE "agencyId"=${agencyId} ORDER BY "createdAt" DESC LIMIT ${Math.min(limit,200)}`).map(r=>({...r,detail:object(r.detail),createdAt:r.createdAt.toISOString()}));}
 async createApiKey(input:{agencyId:string;name:string;prefix:string;secretHash:string;scopes:string[];createdBy:string;expiresAt?:string|null}){const id=uid("key");await prisma.$executeRaw`INSERT INTO agency_api_keys (id,"agencyId",name,prefix,"secretHash",scopes,"createdBy","expiresAt") VALUES (${id},${input.agencyId},${input.name},${input.prefix},${input.secretHash},${input.scopes},${input.createdBy},${input.expiresAt?new Date(input.expiresAt):null})`;return(await this.apiKeys(input.agencyId)).find(x=>x.id===id)!;}
 async apiKeys(agencyId:string){return(await prisma.$queryRaw<KeyRow[]>`SELECT id,"agencyId",name,prefix,scopes,"createdBy","createdAt","lastUsedAt","expiresAt","revokedAt" FROM agency_api_keys WHERE "agencyId"=${agencyId} ORDER BY "createdAt" DESC`).map(this.safeKey);}
 async authenticateApiKey(secretHash:string,now:Date){const rows=await prisma.$queryRaw<KeyRow[]>`UPDATE agency_api_keys SET "lastUsedAt"=${now} WHERE "secretHash"=${secretHash} AND "revokedAt" IS NULL AND ("expiresAt" IS NULL OR "expiresAt">${now}) RETURNING id,"agencyId",name,prefix,scopes,"createdBy","createdAt","lastUsedAt","expiresAt","revokedAt"`;return rows[0]?this.safeKey(rows[0]):null;}
 async revokeApiKey(agencyId:string,id:string){return await prisma.$executeRaw`UPDATE agency_api_keys SET "revokedAt"=${new Date()} WHERE id=${id} AND "agencyId"=${agencyId} AND "revokedAt" IS NULL`===1;}
 async createInvite(input:{agencyId:string;email:string;role:AgencyRole;kind:"seat"|"client_portal";clientId?:string|null;tokenHash:string;createdBy:string;expiresAt:string}){const id=uid("invite");await prisma.$executeRaw`INSERT INTO agency_invites (id,"agencyId",email,role,kind,"clientId","tokenHash","createdBy","expiresAt") VALUES (${id},${input.agencyId},${input.email.toLowerCase()},CAST(${input.role} AS "AgencyRole"),${input.kind},${input.clientId??null},${input.tokenHash},${input.createdBy},${new Date(input.expiresAt)})`;return(await this.invites(input.agencyId)).find(x=>x.id===id)!;}
 async invites(agencyId:string){return(await prisma.$queryRaw<InviteRow[]>`SELECT id,"agencyId",email,role,kind,"clientId","createdBy","createdAt","expiresAt","acceptedAt","acceptedBy","revokedAt" FROM agency_invites WHERE "agencyId"=${agencyId} ORDER BY "createdAt" DESC`).map(mapInvite);}
 async acceptInvite(tokenHash:string,userId:string,email:string,now:Date){return prisma.$transaction(async tx=>{const rows=await tx.$queryRaw<InviteRow[]>`UPDATE agency_invites SET "acceptedAt"=${now},"acceptedBy"=${userId} WHERE "tokenHash"=${tokenHash} AND email=${email.toLowerCase()} AND "acceptedAt" IS NULL AND "revokedAt" IS NULL AND "expiresAt">${now} RETURNING id,"agencyId",email,role,kind,"clientId","createdBy","createdAt","expiresAt","acceptedAt","acceptedBy","revokedAt"`;const row=rows[0];if(!row)return null;if(row.kind==="seat")await tx.$executeRaw`INSERT INTO agency_memberships ("agencyId","userId",role,active,"createdAt") VALUES (${row.agencyId},${userId},CAST(${row.role} AS "AgencyRole"),true,${now}) ON CONFLICT ("agencyId","userId") DO UPDATE SET role=EXCLUDED.role,active=true`;return mapInvite(row);});}
 async hasPortalInvite(agencyId:string,clientId:string,userId:string){const rows=await prisma.$queryRaw<Array<{ok:number}>>`SELECT 1 AS ok FROM agency_invites WHERE "agencyId"=${agencyId} AND "clientId"=${clientId} AND "acceptedBy"=${userId} AND "acceptedAt" IS NOT NULL AND "revokedAt" IS NULL AND kind='client_portal' LIMIT 1`;return!!rows[0];}
 async createReport(input:{agencyId:string;clientOrgId?:string|null;periodStart:string;periodEnd:string;kind:AgencyReport["kind"];title:string;content:Record<string,unknown>;branding:AgencyWorkspace["branding"];createdBy:string}){const id=uid("report");await prisma.$executeRaw`INSERT INTO agency_reports (id,"agencyId","clientOrgId","periodStart","periodEnd",kind,status,title,content,branding,"createdBy") VALUES (${id},${input.agencyId},${input.clientOrgId??null},${new Date(input.periodStart)},${new Date(input.periodEnd)},${input.kind},'ready',${input.title},CAST(${JSON.stringify(input.content)} AS jsonb),CAST(${JSON.stringify(input.branding)} AS jsonb),${input.createdBy})`;return(await this.reports(input.agencyId,200)).find(x=>x.id===id)!;}
 async reports(agencyId:string,limit=100){return(await prisma.$queryRaw<ReportRow[]>`SELECT * FROM agency_reports WHERE "agencyId"=${agencyId} ORDER BY "createdAt" DESC LIMIT ${Math.min(limit,200)}`).map((r):AgencyReport=>({id:r.id,agencyId:r.agencyId,clientOrgId:r.clientOrgId,periodStart:r.periodStart.toISOString(),periodEnd:r.periodEnd.toISOString(),kind:r.kind as AgencyReport["kind"],status:r.status,title:r.title,content:object(r.content),branding:{whiteLabel:Boolean(object(r.branding).whiteLabel),logoUrl:object(r.branding).logoUrl as string|null,primaryColor:String(object(r.branding).primaryColor??"#38e1c3"),accentColor:String(object(r.branding).accentColor??"#5b8cff"),supportEmail:object(r.branding).supportEmail as string|null,customDomain:object(r.branding).customDomain as string|null,emailFromName:object(r.branding).emailFromName as string|null,emailFooter:object(r.branding).emailFooter as string|null},createdBy:r.createdBy,createdAt:r.createdAt.toISOString()}));}
 async report(agencyId:string,id:string){const rows=await prisma.$queryRaw<ReportRow[]>`SELECT * FROM agency_reports WHERE "agencyId"=${agencyId} AND id=${id} LIMIT 1`;return rows[0]?mapReport(rows[0]):null;}
 async createReportShare(input:{agencyId:string;reportId:string;email:string;tokenHash:string;expiresAt:string}){await prisma.$executeRaw`INSERT INTO agency_report_shares (id,"reportId","agencyId",email,"tokenHash","expiresAt") SELECT ${uid("report_share")},r.id,r."agencyId",${input.email},${input.tokenHash},${new Date(input.expiresAt)} FROM agency_reports r WHERE r.id=${input.reportId} AND r."agencyId"=${input.agencyId}`;}
 async authorizeReportShare(agencyId:string,reportId:string,tokenHash:string,now:Date){const rows=await prisma.$queryRaw<Array<{ok:number}>>`SELECT 1 AS ok FROM agency_report_shares WHERE "agencyId"=${agencyId} AND "reportId"=${reportId} AND "tokenHash"=${tokenHash} AND "expiresAt">${now} LIMIT 1`;return!!rows[0];}
 async purgeExpiredReportShares(now:Date){return prisma.$executeRaw`DELETE FROM agency_report_shares WHERE "expiresAt"<=${now}`;}
 async slaEvents(agencyId:string,clientId?:string){const rows=clientId?await prisma.$queryRaw<SlaRow[]>`SELECT s.* FROM agency_sla_events s JOIN agency_clients c ON c.id=s."clientId" WHERE c."agencyId"=${agencyId} AND c.id=${clientId} ORDER BY s."dueAt"`:await prisma.$queryRaw<SlaRow[]>`SELECT s.* FROM agency_sla_events s JOIN agency_clients c ON c.id=s."clientId" WHERE c."agencyId"=${agencyId} ORDER BY s."dueAt"`;return rows.map(mapSla);}
 async upsertSlaEvent(input:{agencyId:string;clientId:string;findingId:string;priority:AgencySlaEvent["priority"];openedAt:string;dueAt:string;lastObservedAt:string;resolved:boolean}){const id=uid("sla"),observed=new Date(input.lastObservedAt),resolvedAt=input.resolved?observed:null,breached=!input.resolved&&new Date(input.dueAt)<observed;await prisma.$executeRaw`INSERT INTO agency_sla_events (id,"clientId","findingId",priority,"openedAt","dueAt","resolvedAt",breached,status,"lastObservedAt") SELECT ${id},c.id,${input.findingId},CAST(${input.priority} AS "Priority"),${new Date(input.openedAt)},${new Date(input.dueAt)},${resolvedAt},${breached},${input.resolved?"resolved":"open"},${observed} FROM agency_clients c WHERE c.id=${input.clientId} AND c."agencyId"=${input.agencyId} ON CONFLICT ("clientId","findingId") DO UPDATE SET priority=EXCLUDED.priority,"lastObservedAt"=EXCLUDED."lastObservedAt",breached=CASE WHEN agency_sla_events.status='resolved' THEN false ELSE EXCLUDED.breached END,status=CASE WHEN EXCLUDED.status='resolved' THEN 'resolved' ELSE agency_sla_events.status END,"resolvedAt"=CASE WHEN EXCLUDED.status='resolved' THEN COALESCE(agency_sla_events."resolvedAt",EXCLUDED."resolvedAt") ELSE agency_sla_events."resolvedAt" END`;const rows=await prisma.$queryRaw<SlaRow[]>`SELECT * FROM agency_sla_events WHERE "clientId"=${input.clientId} AND "findingId"=${input.findingId} LIMIT 1`;if(!rows[0])throw new Error("SLA event client is outside agency scope");return mapSla(rows[0]);}
 async updateSlaEvent(agencyId:string,id:string,patch:{acknowledgeBy?:string;resolve?:boolean;escalated?:boolean}){const at=new Date();await prisma.$executeRaw`UPDATE agency_sla_events s SET status=CASE WHEN ${patch.resolve??false} THEN 'resolved' WHEN ${Boolean(patch.acknowledgeBy)} THEN 'acknowledged' ELSE s.status END,"resolvedAt"=CASE WHEN ${patch.resolve??false} THEN ${at} ELSE s."resolvedAt" END,"acknowledgedAt"=CASE WHEN ${Boolean(patch.acknowledgeBy)} THEN ${at} ELSE s."acknowledgedAt" END,"acknowledgedBy"=COALESCE(${patch.acknowledgeBy??null},s."acknowledgedBy"),"escalatedAt"=CASE WHEN ${patch.escalated??false} THEN ${at} ELSE s."escalatedAt" END FROM agency_clients c WHERE s.id=${id} AND c.id=s."clientId" AND c."agencyId"=${agencyId}`;return(await this.slaEvents(agencyId)).find(item=>item.id===id)??null;}
 private safeKey(r:KeyRow):AgencyApiKey{return{...r,createdAt:r.createdAt.toISOString(),lastUsedAt:r.lastUsedAt?.toISOString()??null,expiresAt:r.expiresAt?.toISOString()??null,revokedAt:r.revokedAt?.toISOString()??null};}
}
