package provider

import (
  "context"
  "encoding/json"
  "errors"
  "fmt"
  "net/url"
  "github.com/hashicorp/terraform-plugin-framework/resource"
  "github.com/hashicorp/terraform-plugin-framework/resource/schema"
  "github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
  "github.com/hashicorp/terraform-plugin-framework/types"
)
type policyResource struct{client *Client};type policyModel struct{ID types.String `tfsdk:"id"`;OrgID types.String `tfsdk:"org_id"`;Name types.String `tfsdk:"name"`;Kind types.String `tfsdk:"kind"`;Description types.String `tfsdk:"description"`;Enabled types.Bool `tfsdk:"enabled"`;Document types.String `tfsdk:"document"`;Version types.Int64 `tfsdk:"version"`}
type policyAPI struct{ID string `json:"id"`;Name string `json:"name"`;Kind string `json:"kind"`;Description *string `json:"description"`;Enabled bool `json:"enabled"`;Document map[string]any `json:"document"`;Version int64 `json:"version"`}
func NewPolicyResource()resource.Resource{return &policyResource{}}
func(r *policyResource)Metadata(_ context.Context,req resource.MetadataRequest,res *resource.MetadataResponse){res.TypeName=req.ProviderTypeName+"_enterprise_policy"}
func(r *policyResource)Schema(_ context.Context,_ resource.SchemaRequest,res *resource.SchemaResponse){res.Schema=schema.Schema{Description:"Versioned enterprise governance or scoring policy.",Attributes:map[string]schema.Attribute{"id":schema.StringAttribute{Computed:true},"org_id":schema.StringAttribute{Required:true},"name":schema.StringAttribute{Required:true},"kind":schema.StringAttribute{Required:true},"description":schema.StringAttribute{Optional:true},"enabled":schema.BoolAttribute{Optional:true,Default:booldefault.StaticBool(true)},"document":schema.StringAttribute{Required:true,Description:"JSON policy document."},"version":schema.Int64Attribute{Computed:true}}}}
func(r *policyResource)Configure(_ context.Context,req resource.ConfigureRequest,res *resource.ConfigureResponse){if req.ProviderData==nil{return};client,ok:=req.ProviderData.(*Client);if !ok{res.Diagnostics.AddError("Unexpected provider data",fmt.Sprintf("got %T",req.ProviderData));return};r.client=client}
func(r *policyResource)Create(ctx context.Context,req resource.CreateRequest,res *resource.CreateResponse){var plan policyModel;res.Diagnostics.Append(req.Plan.Get(ctx,&plan)...);if res.Diagnostics.HasError(){return};var document map[string]any;if err:=json.Unmarshal([]byte(plan.Document.ValueString()),&document);err!=nil{res.Diagnostics.AddError("Invalid policy document",err.Error());return};var out struct{Item policyAPI `json:"item"`};err:=r.client.request(ctx,"POST","/api/enterprise/v1/resources/policies?orgId="+url.QueryEscape(plan.OrgID.ValueString()),map[string]any{"name":plan.Name.ValueString(),"kind":plan.Kind.ValueString(),"description":plan.Description.ValueString(),"enabled":plan.Enabled.ValueBool(),"document":document},false,&out);if err!=nil{res.Diagnostics.AddError("Unable to create policy",err.Error());return};applyPolicy(ctx,&plan,out.Item);res.Diagnostics.Append(res.State.Set(ctx,&plan)...)}
func(r *policyResource)Read(ctx context.Context,req resource.ReadRequest,res *resource.ReadResponse){var state policyModel;res.Diagnostics.Append(req.State.Get(ctx,&state)...);if res.Diagnostics.HasError(){return};var out struct{Item policyAPI `json:"item"`};path:="/api/enterprise/v1/resources/policies?orgId="+url.QueryEscape(state.OrgID.ValueString())+"&id="+url.QueryEscape(state.ID.ValueString());if err:=r.client.request(ctx,"GET",path,nil,false,&out);err!=nil{var apiErr *APIError;if errors.As(err,&apiErr)&&apiErr.StatusCode==404{res.State.RemoveResource(ctx);return};res.Diagnostics.AddError("Unable to read policy",err.Error());return};applyPolicy(ctx,&state,out.Item);res.Diagnostics.Append(res.State.Set(ctx,&state)...)}
func(r *policyResource)Update(ctx context.Context,req resource.UpdateRequest,res *resource.UpdateResponse){var plan policyModel;res.Diagnostics.Append(req.Plan.Get(ctx,&plan)...);if res.Diagnostics.HasError(){return};var document map[string]any;if err:=json.Unmarshal([]byte(plan.Document.ValueString()),&document);err!=nil{res.Diagnostics.AddError("Invalid policy document",err.Error());return};var out struct{Item policyAPI `json:"item"`};if err:=r.client.request(ctx,"PATCH","/api/enterprise/v1/resources/policies?orgId="+url.QueryEscape(plan.OrgID.ValueString()),map[string]any{"id":plan.ID.ValueString(),"name":plan.Name.ValueString(),"description":plan.Description.ValueString(),"enabled":plan.Enabled.ValueBool(),"document":document},false,&out);err!=nil{res.Diagnostics.AddError("Unable to update policy",err.Error());return};applyPolicy(ctx,&plan,out.Item);res.Diagnostics.Append(res.State.Set(ctx,&plan)...)}
func(r *policyResource)Delete(ctx context.Context,req resource.DeleteRequest,res *resource.DeleteResponse){var state policyModel;res.Diagnostics.Append(req.State.Get(ctx,&state)...);if res.Diagnostics.HasError(){return};path:="/api/enterprise/v1/resources/policies?orgId="+url.QueryEscape(state.OrgID.ValueString())+"&id="+url.QueryEscape(state.ID.ValueString());if err:=r.client.request(ctx,"DELETE",path,nil,false,nil);err!=nil{res.Diagnostics.AddError("Unable to delete policy",err.Error())}}
func applyPolicy(ctx context.Context,state *policyModel,item policyAPI){state.ID=types.StringValue(item.ID);state.Name=types.StringValue(item.Name);state.Kind=types.StringValue(item.Kind);if item.Description!=nil{state.Description=types.StringValue(*item.Description)}else{state.Description=types.StringNull()};state.Enabled=types.BoolValue(item.Enabled);state.Version=types.Int64Value(item.Version);raw,_:=json.Marshal(item.Document);state.Document=types.StringValue(string(raw));_ = ctx}
var _ resource.ResourceWithConfigure=&policyResource{}
