package provider

import (
  "context"
  "fmt"
  "net/url"
  "github.com/hashicorp/terraform-plugin-framework/resource"
  "github.com/hashicorp/terraform-plugin-framework/resource/schema"
  "github.com/hashicorp/terraform-plugin-framework/types"
)
type workspaceResource struct{client *Client};type workspaceModel struct{ID types.String `tfsdk:"id"`;OrgID types.String `tfsdk:"org_id"`;OwnerUserID types.String `tfsdk:"owner_user_id"`;LicenseStatus types.String `tfsdk:"license_status"`;LicensedSeats types.Int64 `tfsdk:"licensed_seats"`;DataRegion types.String `tfsdk:"data_region"`;Features types.Set `tfsdk:"features"`}
func NewWorkspaceResource()resource.Resource{return &workspaceResource{}}
func(r *workspaceResource)Metadata(_ context.Context,req resource.MetadataRequest,res *resource.MetadataResponse){res.TypeName=req.ProviderTypeName+"_enterprise_workspace"}
func(r *workspaceResource)Schema(_ context.Context,_ resource.SchemaRequest,res *resource.SchemaResponse){res.Schema=schema.Schema{Description:"Provision and license an OUTSIDE Enterprise workspace.",Attributes:map[string]schema.Attribute{"id":schema.StringAttribute{Computed:true},"org_id":schema.StringAttribute{Required:true},"owner_user_id":schema.StringAttribute{Required:true},"license_status":schema.StringAttribute{Optional:true,Computed:true},"licensed_seats":schema.Int64Attribute{Required:true},"data_region":schema.StringAttribute{Required:true},"features":schema.SetAttribute{Optional:true,Computed:true,ElementType:types.StringType}}}}
func(r *workspaceResource)Configure(_ context.Context,req resource.ConfigureRequest,res *resource.ConfigureResponse){if req.ProviderData==nil{return};client,ok:=req.ProviderData.(*Client);if !ok{res.Diagnostics.AddError("Unexpected provider data",fmt.Sprintf("got %T",req.ProviderData));return};r.client=client}
func(r *workspaceResource)Create(ctx context.Context,req resource.CreateRequest,res *resource.CreateResponse){var plan workspaceModel;res.Diagnostics.Append(req.Plan.Get(ctx,&plan)...);if res.Diagnostics.HasError(){return};var out struct{Workspace struct{ID,OrgID,LicenseStatus,DataRegion string;LicensedSeats int64;Features []string}};err:=r.client.request(ctx,"POST","/api/enterprise/provisioning",map[string]any{"orgId":plan.OrgID.ValueString(),"ownerUserId":plan.OwnerUserID.ValueString(),"licensedSeats":plan.LicensedSeats.ValueInt64(),"dataRegion":plan.DataRegion.ValueString()},true,&out);if err!=nil{res.Diagnostics.AddError("Unable to provision workspace",err.Error());return};plan.ID=types.StringValue(out.Workspace.ID);plan.LicenseStatus=types.StringValue(out.Workspace.LicenseStatus);plan.Features,_=types.SetValueFrom(ctx,types.StringType,out.Workspace.Features);res.Diagnostics.Append(res.State.Set(ctx,&plan)...)}
func(r *workspaceResource)Read(ctx context.Context,req resource.ReadRequest,res *resource.ReadResponse){var state workspaceModel;res.Diagnostics.Append(req.State.Get(ctx,&state)...);if res.Diagnostics.HasError(){return};var out struct{Workspace struct{ID,OrgID,LicenseStatus,DataRegion string;LicensedSeats int64;Features []string}};if err:=r.client.request(ctx,"GET","/api/enterprise/provisioning?orgId="+url.QueryEscape(state.OrgID.ValueString()),nil,true,&out);err!=nil{res.Diagnostics.AddError("Unable to read workspace",err.Error());return};state.ID=types.StringValue(out.Workspace.ID);state.LicenseStatus=types.StringValue(out.Workspace.LicenseStatus);state.LicensedSeats=types.Int64Value(out.Workspace.LicensedSeats);state.DataRegion=types.StringValue(out.Workspace.DataRegion);state.Features,_=types.SetValueFrom(ctx,types.StringType,out.Workspace.Features);res.Diagnostics.Append(res.State.Set(ctx,&state)...)}
func(r *workspaceResource)Update(ctx context.Context,req resource.UpdateRequest,res *resource.UpdateResponse){var plan workspaceModel;res.Diagnostics.Append(req.Plan.Get(ctx,&plan)...);if res.Diagnostics.HasError(){return};var features []string;res.Diagnostics.Append(plan.Features.ElementsAs(ctx,&features,false)...);payload:=map[string]any{"orgId":plan.OrgID.ValueString(),"licensedSeats":plan.LicensedSeats.ValueInt64(),"features":features};if !plan.LicenseStatus.IsNull()&&!plan.LicenseStatus.IsUnknown(){payload["licenseStatus"]=plan.LicenseStatus.ValueString()};var out struct{Workspace struct{ID,OrgID,LicenseStatus,DataRegion string;LicensedSeats int64;Features []string}};if err:=r.client.request(ctx,"PATCH","/api/enterprise/provisioning",payload,true,&out);err!=nil{res.Diagnostics.AddError("Unable to update workspace",err.Error());return};plan.ID=types.StringValue(out.Workspace.ID);plan.LicenseStatus=types.StringValue(out.Workspace.LicenseStatus);plan.LicensedSeats=types.Int64Value(out.Workspace.LicensedSeats);plan.DataRegion=types.StringValue(out.Workspace.DataRegion);plan.Features,_=types.SetValueFrom(ctx,types.StringType,out.Workspace.Features);res.Diagnostics.Append(res.State.Set(ctx,&plan)...)}
func(r *workspaceResource)Delete(ctx context.Context,req resource.DeleteRequest,res *resource.DeleteResponse){var state workspaceModel;res.Diagnostics.Append(req.State.Get(ctx,&state)...);if res.Diagnostics.HasError(){return};if err:=r.client.request(ctx,"PATCH","/api/enterprise/provisioning",map[string]any{"orgId":state.OrgID.ValueString(),"licenseStatus":"suspended"},true,nil);err!=nil{res.Diagnostics.AddError("Unable to suspend workspace",err.Error())}}
var _ resource.ResourceWithConfigure=&workspaceResource{}
