import { NextRequest, NextResponse } from "next/server";
import { enterpriseAccess } from "@/lib/enterprise/access";
import { hashIp } from "@/lib/enterprise/audit";
import { getEnterpriseStore } from "@/lib/enterprise/store";
import { type EnterpriseResourceKind } from "@/lib/enterprise/types";
import { RESOURCE_PERMISSION, sanitizePatch, sanitizeResource } from "@/lib/enterprise/validation";
import { readLimitedJson, RequestBodyError } from "@/lib/http/body";
import { clientIdentity, requireBudgets } from "@/lib/security/ratelimit";
import { approvalRequired, validApproval } from "@/lib/enterprise/approval";
import type { EnterpriseApproval, EnterprisePolicy } from "@/lib/enterprise/types";
import { getAuthStore } from "@/lib/auth";
import type { EnterpriseStore } from "@/lib/enterprise/store-model";

export const runtime = "nodejs"; export const dynamic = "force-dynamic";
const kinds = new Set<EnterpriseResourceKind>(["roles", "bindings", "units", "ownership", "policies", "approvals", "exceptions", "tickets", "exports", "flags"]);
const json = (body: unknown, status = 200) => NextResponse.json(body, { status, headers: { "cache-control": "no-store" } });
async function context(req: NextRequest, raw: string, override?: "approvals:decide") { const kind = raw as EnterpriseResourceKind; if (!kinds.has(kind)) return null; const access = await enterpriseAccess(req, override ?? RESOURCE_PERMISSION[kind], new URL(req.url).searchParams.get("orgId")); return access ? { kind, access } : null; }
async function body(req: NextRequest) { return readLimitedJson(req, 60_000); }
async function validateReferences(kind: EnterpriseResourceKind, input: Record<string, unknown>, store: EnterpriseStore, workspaceId: string, orgId: string) { const exists = async (resource: EnterpriseResourceKind, id: unknown) => typeof id === "string" && (await store.list(workspaceId, resource)).some((item) => item.id === id); if (kind === "bindings") { if (!await exists("roles", input.roleId)) throw new Error("Role belongs to another workspace or does not exist."); if (input.principalType === "group" && !await exists("directoryGroups", input.principalId)) throw new Error("Group belongs to another workspace or does not exist."); if (input.principalType === "service" && !await exists("apiTokens", input.principalId)) throw new Error("Service principal token does not exist."); if (input.principalType === "user" && !await (await getAuthStore()).getMembership(String(input.principalId), orgId)) throw new Error("User is not an active organization member."); if (input.scopeType === "department" && !await exists("units", input.scopeId)) throw new Error("Department scope does not exist in this workspace."); } if (kind === "units" && input.parentId && !await exists("units", input.parentId)) throw new Error("Parent unit belongs to another workspace or does not exist."); if (kind === "ownership") { if (input.ownerType === "group" && !await exists("directoryGroups", input.ownerId) || input.ownerType === "department" && !await exists("units", input.ownerId) || input.ownerType === "user" && !await (await getAuthStore()).getMembership(String(input.ownerId), orgId)) throw new Error("Owner belongs to another workspace or does not exist."); } if (kind === "exceptions" && input.policyId && !await exists("policies", input.policyId)) throw new Error("Risk exception policy does not exist in this workspace."); if (kind === "exports" && input.destinationIntegrationId && !await exists("integrations", input.destinationIntegrationId)) throw new Error("Export destination does not exist in this workspace."); if (kind === "approvals") for (const approver of input.approverIds as string[]) if (!await (await getAuthStore()).getMembership(approver, orgId)) throw new Error("Every approver must be an active organization member."); }

export async function GET(req: NextRequest, { params }: { params: Promise<{ kind: string }> }) { const resolved = await context(req, (await params).kind); if (!resolved) return json({ error: "Enterprise permission required" }, 403); const url = new URL(req.url), store = await getEnterpriseStore(), id = url.searchParams.get("id"); if (id) { const item = await store.resource(resolved.access.workspace.id, resolved.kind, id); return item ? json({ item }) : json({ error: "Enterprise resource not found" }, 404); } const limit = Math.max(1, Math.min(200, Number(url.searchParams.get("limit") ?? 100))), items = await store.list(resolved.access.workspace.id, resolved.kind, { limit: limit + 1, afterId: url.searchParams.get("after") ?? undefined }), hasMore = items.length > limit, selected = items.slice(0, limit); return json({ items: selected, nextCursor: hasMore ? selected.at(-1)?.id ?? null : null }); }
export async function POST(req: NextRequest, { params }: { params: Promise<{ kind: string }> }) { const resolved = await context(req, (await params).kind); if (!resolved) return json({ error: "Enterprise permission required" }, 403); if (!(await requireBudgets([{ key: `enterprise:write:${resolved.access.workspace.id}`, limit: 120, windowMs: 60_000 }, { key: `enterprise:write:${clientIdentity(req)}`, limit: 180, windowMs: 60_000 }])).ok) return json({ error: "Write rate exceeded" }, 429); try { const input = sanitizeResource(resolved.kind, await body(req), resolved.access.actorId), store = await getEnterpriseStore(); await validateReferences(resolved.kind, input, store, resolved.access.workspace.id, resolved.access.workspace.orgId); const item = await store.createAudited(resolved.access.workspace.id, resolved.kind, input as never, { actorType: resolved.access.actorType, actorId: resolved.access.actorId, action: `enterprise.${resolved.kind}.created`, resourceType: resolved.kind, requestId: req.headers.get("x-request-id"), ipHash: hashIp(clientIdentity(req)), detail: { fields: Object.keys(input) } }); return json({ item }, 201); } catch (error) { return json({ error: (error as Error).message }, error instanceof RequestBodyError ? error.status : 422); } }
export async function PATCH(req: NextRequest, { params }: { params: Promise<{ kind: string }> }) { const raw = (await params).kind; const resolved = await context(req, raw, ["approvals", "exceptions"].includes(raw) ? "approvals:decide" : undefined); if (!resolved) return json({ error: "Enterprise permission required" }, 403); try { const value = await body(req), data = value && typeof value === "object" ? value as Record<string, unknown> : {}, id = typeof data.id === "string" ? data.id : ""; if (!id) return json({ error: "Resource id is required" }, 422); const store = await getEnterpriseStore(), existing = await store.resource(resolved.access.workspace.id, resolved.kind, id); if (!existing || existing.system === true) return json({ error: "Resource is missing or immutable" }, 404); if (resolved.kind === "approvals" && (existing.requestedBy === resolved.access.actorId || Array.isArray(existing.approverIds) && !existing.approverIds.includes(resolved.access.actorId)) || resolved.kind === "exceptions" && existing.requestedBy === resolved.access.actorId && data.status === "approved") return json({ error: "Approval requires an assigned, independent approver" }, 403); const action = `enterprise.${resolved.kind}.updated`, policies = await store.list<EnterprisePolicy>(resolved.access.workspace.id, "policies"); if (approvalRequired(policies, action) && !validApproval(await store.list<EnterpriseApproval>(resolved.access.workspace.id, "approvals"), typeof data.approvalId === "string" ? data.approvalId : null, action, id)) return json({ error: "An approved workflow decision is required for this change" }, 409); const patch = sanitizePatch(resolved.kind, data, resolved.access.actorId); await validateReferences(resolved.kind, { ...existing, ...patch }, store, resolved.access.workspace.id, resolved.access.workspace.orgId); if (resolved.kind === "policies") patch.version = Number(existing.version ?? 0) + 1; const item = await store.updateAudited(resolved.access.workspace.id, resolved.kind, id, patch, { actorType: resolved.access.actorType, actorId: resolved.access.actorId, action, resourceType: resolved.kind, requestId: req.headers.get("x-request-id"), ipHash: hashIp(clientIdentity(req)), detail: { fields: Object.keys(patch), approvalId: data.approvalId ?? null } }); return json({ item }); } catch (error) { return json({ error: (error as Error).message }, error instanceof RequestBodyError ? error.status : 422); } }
export async function DELETE(req: NextRequest, { params }: { params: Promise<{ kind: string }> }) { const resolved = await context(req, (await params).kind); if (!resolved) return json({ error: "Enterprise permission required" }, 403); const url = new URL(req.url), id = url.searchParams.get("id") ?? "", store = await getEnterpriseStore(), existing = await store.resource(resolved.access.workspace.id, resolved.kind, id); if (!existing || existing.system === true) return json({ error: "Resource is missing or immutable" }, 404); const action = `enterprise.${resolved.kind}.deleted`, policies = await store.list<EnterprisePolicy>(resolved.access.workspace.id, "policies"); if (approvalRequired(policies, action) && !validApproval(await store.list<EnterpriseApproval>(resolved.access.workspace.id, "approvals"), url.searchParams.get("approvalId"), action, id)) return json({ error: "An approved workflow decision is required for deletion" }, 409); const removed = await store.removeAudited(resolved.access.workspace.id, resolved.kind, id, { actorType: resolved.access.actorType, actorId: resolved.access.actorId, action, resourceType: resolved.kind, requestId: req.headers.get("x-request-id"), ipHash: hashIp(clientIdentity(req)), detail: { approvalId: url.searchParams.get("approvalId") } }); return json({ removed }); }
