import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { AgencyReport } from "@/lib/agency/types";

const styles = StyleSheet.create({ page: { fontFamily: "Helvetica", color: "#101722", fontSize: 9, paddingBottom: 40 }, band: { backgroundColor: "#080d14", color: "#edf4ff", padding: 30, flexDirection: "row", justifyContent: "space-between" }, brand: { fontFamily: "Helvetica-Bold", fontSize: 15, letterSpacing: 2 }, sub: { marginTop: 4, color: "#91a0b8", fontSize: 8, letterSpacing: 1 }, body: { padding: 30 }, title: { fontFamily: "Helvetica-Bold", fontSize: 23 }, muted: { color: "#708096", marginTop: 5 }, stats: { flexDirection: "row", gap: 8, marginTop: 20 }, stat: { flex: 1, border: "1 solid #dfe6ef", borderRadius: 6, padding: 10 }, value: { fontFamily: "Helvetica-Bold", fontSize: 18 }, label: { color: "#708096", fontSize: 7, textTransform: "uppercase", marginTop: 3 }, heading: { fontFamily: "Helvetica-Bold", fontSize: 10, color: "#435269", textTransform: "uppercase", letterSpacing: 1, marginTop: 22, marginBottom: 8 }, item: { border: "1 solid #dfe6ef", borderRadius: 6, padding: 10, marginBottom: 7 }, itemTitle: { fontFamily: "Helvetica-Bold", fontSize: 10 }, itemText: { color: "#435269", lineHeight: 1.4, marginTop: 4 }, footer: { position: "absolute", bottom: 16, left: 30, right: 30, borderTop: "1 solid #dfe6ef", paddingTop: 5, color: "#8190a4", fontSize: 7, flexDirection: "row", justifyContent: "space-between" } });
const number = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value : 0;
const text = (value: unknown) => typeof value === "string" ? value.slice(0, 2000) : "";
const list = (value: unknown) => Array.isArray(value) ? value.slice(0, 30) as Array<Record<string, unknown>> : [];

export function AgencyReportDocument({ report }: { report: AgencyReport }) {
  const content = report.content; const changes = list(content.recentChanges); const brand = report.branding.whiteLabel ? report.branding.emailFromName || "Security Operations" : "OUTSIDE Agency"; const source = report.branding.whiteLabel ? "" : " collected by OUTSIDE";
  return <Document title={report.title} author={brand}><Page size="A4" style={styles.page} wrap><View style={{ ...styles.band, borderBottom: `4 solid ${report.branding.primaryColor}` }} fixed><View><Text style={styles.brand}>{brand}</Text><Text style={styles.sub}>{report.kind.toUpperCase()} SECURITY REPORT</Text></View><Text>{new Date(report.periodEnd).toLocaleDateString()}</Text></View><View style={styles.body}><Text style={styles.title}>{report.title}</Text><Text style={styles.muted}>{text(content.client)} · {new Date(report.periodStart).toLocaleDateString()} – {new Date(report.periodEnd).toLocaleDateString()}</Text><View style={styles.stats}><View style={styles.stat}><Text style={styles.value}>{number(content.assets)}</Text><Text style={styles.label}>Observed assets</Text></View><View style={styles.stat}><Text style={styles.value}>{number(content.openRecommendations)}</Text><Text style={styles.label}>Open reviews</Text></View><View style={styles.stat}><Text style={styles.value}>{number(content.critical)}</Text><Text style={styles.label}>Critical</Text></View><View style={styles.stat}><Text style={styles.value}>{number(content.targets)}</Text><Text style={styles.label}>Targets</Text></View></View><Text style={styles.heading}>Executive overview</Text><Text style={styles.itemText}>This report summarizes deterministic, publicly observable external-surface evidence{source}. It does not claim exploitation or compromise. Review priorities reflect observed exposure and configured service policy.</Text><Text style={styles.heading}>Important external changes</Text>{changes.map((change, index) => <View key={`${text(change.id)}-${index}`} style={styles.item} wrap={false}><Text style={styles.itemTitle}>{text(change.title) || "External change"}</Text><Text style={styles.itemText}>{text(change.summary)}</Text><Text style={{ ...styles.itemText, color: report.branding.primaryColor }}>{text(change.severity).toUpperCase()}</Text></View>)}{!changes.length && <Text style={styles.itemText}>No important changes were recorded for this reporting period.</Text>}</View><View style={styles.footer} fixed><Text>{report.branding.emailFooter || "External exposure intelligence · deterministic evidence"}</Text><Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} /></View></Page></Document>;
}
