import { randomUUID } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { enterpriseAccess } from "@/lib/enterprise/access";
import { queueEnterpriseEvent } from "@/lib/enterprise/delivery";
import { getEnterpriseStore } from "@/lib/enterprise/store";
import type { EnterpriseEventEnvelope } from "@/lib/enterprise/providers";
import { readLimitedJson, RequestBodyError } from "@/lib/http/body";
import { clientIdentity, requireBudgets } from "@/lib/security/ratelimit";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
export async function POST(req: NextRequest) { try { const body = await readLimitedJson(req, 100_000) as Record<string, unknown>, resource = body.resource && typeof body.resource === "object" ? body.resource as Record<string, unknown> : {}, evidence = body.evidence && typeof body.evidence === "object" ? body.evidence as Record<string, unknown> : {}; if (!body.type || !body.title || !resource.id || !resource.type || !Object.keys(evidence).length) return NextResponse.json({ error: "Type, title, resource and deterministic evidence references are required" }, { status: 422 }); const resourceType = String(resource.type).slice(0, 80), resourceId = String(resource.id).slice(0, 240), access = await enterpriseAccess(req, "integrations:manage", new URL(req.url).searchParams.get("orgId"), { type: `${resourceType}Ids`, id: resourceId }); if (!access) return NextResponse.json({ error: "Integration permission or token scope required" }, { status: 403 }); if (!(await requireBudgets([{ key: `enterprise:event:${access.workspace.id}`, limit: 600, windowMs: 60_000 }, { key: `enterprise:event:${clientIdentity(req)}`, limit: 900, windowMs: 60_000 }])).ok) return NextResponse.json({ error: "Event rate exceeded" }, { status: 429 }); const event: EnterpriseEventEnvelope = { id: typeof body.id === "string" ? body.id.slice(0, 240) : `evt_${randomUUID()}`, occurredAt: typeof body.occurredAt === "string" ? new Date(body.occurredAt).toISOString() : new Date().toISOString(), organizationId: access.workspace.orgId, type: String(body.type).slice(0, 100), severity: ["info", "low", "medium", "high", "critical"].includes(String(body.severity)) ? String(body.severity) : "medium", title: String(body.title).slice(0, 300), description: String(body.description ?? "").slice(0, 5000), resource: { type: resourceType, id: resourceId, name: typeof resource.name === "string" ? resource.name.slice(0, 300) : undefined }, evidence }; const store = await getEnterpriseStore(), queued = await queueEnterpriseEvent(store, access.workspace.id, event, { actorType: access.actorType, actorId: access.actorId, action: "enterprise.event.queued", resourceType: event.resource.type, requestId: req.headers.get("x-request-id"), ipHash: null, detail: { eventId: event.id, resourceId: event.resource.id } }); return NextResponse.json({ eventId: event.id, queued }, { status: 202, headers: { "cache-control": "no-store" } }); } catch (error) { return NextResponse.json({ error: (error as Error).message }, { status: error instanceof RequestBodyError ? error.status : 422 }); } }
