import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/db/prisma";
import { PrismaAgencyStore } from "@/lib/agency/prisma-store";

const suffix=randomUUID().slice(0,8),ownerOrg=`agency_owner_${suffix}`,clientOrg=`agency_client_${suffix}`,otherOrg=`agency_other_${suffix}`,ownerUser=`agency_user_${suffix}`,portalUser=`portal_user_${suffix}`;
describe("Agency PostgreSQL workflows",()=>{const store=new PrismaAgencyStore();let agencyId="",clientId="";
  beforeAll(async()=>{await prisma.$executeRaw`INSERT INTO users (id,email,name,"passwordHash","emailVerifiedAt","sessionVersion","createdAt") VALUES (${ownerUser},${`owner-${suffix}@test.local`},'Owner','hash',NOW(),0,NOW()),(${portalUser},${`portal-${suffix}@test.local`},'Portal','hash',NOW(),0,NOW())`;for(const [id,name,slug] of [[ownerOrg,"Agency Owner",`agency-owner-${suffix}`],[clientOrg,"Client",`client-${suffix}`],[otherOrg,"Other",`other-${suffix}`]])await prisma.$executeRaw`INSERT INTO organizations (id,name,slug,plan,"createdAt") VALUES (${id},${name},${slug},CAST('agency' AS "Plan"),NOW())`;});
  afterAll(async()=>{if(agencyId)await prisma.$executeRaw`DELETE FROM agency_workspaces WHERE id=${agencyId}`;await prisma.$executeRaw`DELETE FROM organizations WHERE id IN (${ownerOrg},${clientOrg},${otherOrg})`;await prisma.$executeRaw`DELETE FROM users WHERE id IN (${ownerUser},${portalUser})`;await prisma.$disconnect();});
  it("persists tenant isolation, idempotent jobs, notes and portal grants",async()=>{const workspace=await store.createWorkspace({ownerOrgId:ownerOrg,ownerUserId:ownerUser,name:"Agency",slug:`agency-${suffix}`});agencyId=workspace.id;const linked=await store.addClient({agencyId,orgId:clientOrg,organizationName:"Client",organizationSlug:`client-${suffix}`});expect(linked).not.toBeNull();clientId=linked!.id;expect(await store.updateClient("wrong_agency",clientId,{serviceTier:"breached"})).toBeNull();const job1=await store.createJob({agencyId,type:"report",idempotencyKey:`job-${suffix}`,clientOrgIds:[clientOrg],payload:{period:"weekly"},createdBy:ownerUser}),job2=await store.createJob({agencyId,type:"report",idempotencyKey:`job-${suffix}`,clientOrgIds:[clientOrg],payload:{period:"weekly"},createdBy:ownerUser});expect(job2.id).toBe(job1.id);const note=await store.createNote({agencyId,clientId,authorId:ownerUser,body:"Deterministic review note",visibility:"internal"});expect((await store.notes(agencyId,clientId))[0]?.id).toBe(note.id);const invite=await store.createInvite({agencyId,email:`portal-${suffix}@test.local`,role:"viewer",kind:"client_portal",clientId,tokenHash:`hash-${suffix}`,createdBy:ownerUser,expiresAt:new Date(Date.now()+86_400_000).toISOString()});expect(invite.clientId).toBe(clientId);expect(await store.acceptInvite(`hash-${suffix}`,portalUser,`portal-${suffix}@test.local`,new Date())).not.toBeNull();expect(await store.hasPortalInvite(agencyId,clientId,portalUser)).toBe(true);});
});
