import { NextRequest, NextResponse } from "next/server";
import { enterpriseAccess } from "@/lib/enterprise/access";
import { verifyAuditChain } from "@/lib/enterprise/audit";
import { getEnterpriseStore } from "@/lib/enterprise/store";
import type { EnterpriseAuditEvent } from "@/lib/enterprise/types";
import { csvCell } from "@/lib/export/csv";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
async function completeAudit(workspaceId: string, cap = 100_000): Promise<{ events: EnterpriseAuditEvent[]; complete: boolean }> { const store = await getEnterpriseStore(), events: EnterpriseAuditEvent[] = []; let after: string | undefined; while (events.length < cap) { const rows = await store.auditEvents(workspaceId, Math.min(5000, cap - events.length), after); if (!rows.length) return { events, complete: true }; events.push(...rows); after = rows.at(-1)!.sequence; if (rows.length < 5000) return { events, complete: true }; } return { events, complete: !(await store.auditEvents(workspaceId, 1, after)).length }; }
export async function GET(req: NextRequest) { const url = new URL(req.url), format = url.searchParams.get("format") ?? "json", required = format === "json" ? "audit:read" : "audit:export", access = await enterpriseAccess(req, required, url.searchParams.get("orgId")); if (!access) return NextResponse.json({ error: "Audit permission required" }, { status: 403 }); const loaded = await completeAudit(access.workspace.id), events = loaded.events; if (!loaded.complete) return NextResponse.json({ error: "Audit export exceeds the single-export limit; use scheduled segmented exports.", loaded: events.length }, { status: 413 }); const integrity = verifyAuditChain(events); if (!integrity.valid) return NextResponse.json({ error: "Audit integrity verification failed", integrity }, { status: 409, headers: { "cache-control": "no-store" } }); const headers = { "cache-control": "no-store", "x-outside-audit-head": integrity.head ?? "GENESIS", "x-outside-audit-count": String(events.length) }; if (format === "ndjson") return new NextResponse(events.map((event) => JSON.stringify(event)).join("\n"), { headers: { ...headers, "content-type": "application/x-ndjson", "content-disposition": `attachment; filename="outside-audit-${access.workspace.orgId}.ndjson"` } }); if (format === "csv") { const columns = ["sequence", "createdAt", "actorType", "actorId", "action", "resourceType", "resourceId", "requestId", "ipHash", "previousHash", "hash", "detail"], rows = [columns.join(","), ...events.map((event) => columns.map((column) => csvCell(column === "detail" ? JSON.stringify(event.detail) : event[column])).join(","))]; return new NextResponse(rows.join("\r\n"), { headers: { ...headers, "content-type": "text/csv; charset=utf-8", "content-disposition": `attachment; filename="outside-audit-${access.workspace.orgId}.csv"` } }); } return NextResponse.json({ schema: "com.outside.enterprise.audit/v1", generatedAt: new Date().toISOString(), integrity, events }, { headers }); }
