import { NextRequest, NextResponse } from "next/server";
import { enterpriseAccess } from "@/lib/enterprise/access";
import { hashIp } from "@/lib/enterprise/audit";
import { opaqueToken } from "@/lib/enterprise/crypto";
import { getEnterpriseStore } from "@/lib/enterprise/store";
import { ENTERPRISE_PERMISSIONS, type EnterpriseApiToken, type EnterprisePermission } from "@/lib/enterprise/types";
import { readLimitedJson, RequestBodyError } from "@/lib/http/body";
import { clientIdentity, requireBudgets } from "@/lib/security/ratelimit";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
const json = (body: unknown, status = 200) => NextResponse.json(body, { status, headers: { "cache-control": "no-store" } });
function tokenScopes(value: unknown): Record<string, string[]> { if (value === undefined) return {}; if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Token scopes must be an object of identifier arrays."); const scopes: Record<string, string[]> = {}; for (const [key, raw] of Object.entries(value as Record<string, unknown>).slice(0, 20)) { if (!/^[a-z][a-zA-Z0-9]{0,49}Ids$/.test(key) || !Array.isArray(raw)) throw new Error("Token scope keys must end in Ids and contain an array."); scopes[key] = [...new Set(raw.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter(Boolean))].slice(0, 1000); if (scopes[key]!.length !== raw.length) throw new Error("Token scope identifiers must be unique non-empty strings."); } return scopes; }
export async function GET(req: NextRequest) { const access = await enterpriseAccess(req, "tokens:manage", new URL(req.url).searchParams.get("orgId")); if (!access) return json({ error: "Token management permission required" }, 403); const items = (await (await getEnterpriseStore()).list<EnterpriseApiToken>(access.workspace.id, "apiTokens")).map(({ secretHash: _hash, ...item }) => item); return json({ items }); }
export async function POST(req: NextRequest) { const access = await enterpriseAccess(req, "tokens:manage", new URL(req.url).searchParams.get("orgId")); if (!access) return json({ error: "Token management permission required" }, 403); if (!(await requireBudgets([{ key: `enterprise:token:${access.workspace.id}`, limit: 20, windowMs: 86_400_000 }, { key: `enterprise:token:${clientIdentity(req)}`, limit: 30, windowMs: 86_400_000 }])).ok) return json({ error: "Token creation limit exceeded" }, 429); try { const body = await readLimitedJson(req, 20_000) as Record<string, unknown>, name = typeof body.name === "string" ? body.name.trim().slice(0, 100) : "", permissions = Array.isArray(body.permissions) ? [...new Set(body.permissions.filter((item): item is EnterprisePermission => ENTERPRISE_PERMISSIONS.includes(item as EnterprisePermission)))] : []; if (!name || !permissions.length || !permissions.every((permission) => access.permissions.has(permission))) return json({ error: "Name and delegable permissions are required" }, 422); const expiresAt = typeof body.expiresAt === "string" ? new Date(body.expiresAt).toISOString() : null; if (expiresAt && new Date(expiresAt) <= new Date()) return json({ error: "Token expiry must be in the future" }, 422); const secret = opaqueToken("out_enterprise"), store = await getEnterpriseStore(); const item = await store.createAudited<EnterpriseApiToken>(access.workspace.id, "apiTokens", { name, prefix: secret.prefix, secretHash: secret.hash, permissions, scopes: tokenScopes(body.scopes), createdBy: access.actorId, expiresAt, lastUsedAt: null, revokedAt: null }, { actorType: access.actorType, actorId: access.actorId, action: "enterprise.api_token.created", resourceType: "api_token", requestId: req.headers.get("x-request-id"), ipHash: hashIp(clientIdentity(req)), detail: { name, permissions, prefix: secret.prefix } }); const { secretHash: _hash, ...safe } = item; return json({ item: safe, token: secret.token }, 201); } catch (error) { return json({ error: (error as Error).message }, error instanceof RequestBodyError ? error.status : 422); } }
export async function DELETE(req: NextRequest) { const access = await enterpriseAccess(req, "tokens:manage", new URL(req.url).searchParams.get("orgId")); if (!access) return json({ error: "Token management permission required" }, 403); const id = new URL(req.url).searchParams.get("id") ?? "", store = await getEnterpriseStore(); const item = await store.updateAudited<EnterpriseApiToken>(access.workspace.id, "apiTokens", id, { revokedAt: new Date().toISOString() }, { actorType: access.actorType, actorId: access.actorId, action: "enterprise.api_token.revoked", resourceType: "api_token", requestId: req.headers.get("x-request-id"), ipHash: hashIp(clientIdentity(req)), detail: {} }); if (!item) return json({ error: "Token not found" }, 404); return json({ revoked: true }); }
