import Link from "next/link";
import { redirect } from "next/navigation";
import { EnterpriseConsole } from "@/components/enterprise/EnterpriseConsole";
import { LogoutButton } from "@/components/account/AccountControls";
import { Wordmark } from "@/components/Wordmark";
import { enterpriseAccess } from "@/lib/enterprise/access";
import { getEnterpriseStore } from "@/lib/enterprise/store";
export const dynamic = "force-dynamic"; export const metadata = { title: "Enterprise · OUTSIDE", description: "Identity, governance and security operations control plane." };
export default async function EnterprisePage({ searchParams }: { searchParams: Promise<{ orgId?: string }> }) { const orgId = (await searchParams).orgId ?? null, access = await enterpriseAccess(null, "enterprise:read", orgId); if (!access) redirect("/account"); const overview = await (await getEnterpriseStore()).overview(access.workspace.id); if (!overview) redirect("/account"); const organizationName = access.session?.memberships.find((item) => item.org.id === access.workspace.orgId)?.org.name ?? "Enterprise workspace"; return <div className="min-h-screen"><header className="sticky top-0 z-30 border-b border-line bg-base-950/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 md:px-8"><div className="flex items-center gap-4"><Link href="/"><Wordmark className="h-6"/></Link><span className="mono rounded-sm border border-signal/20 bg-signal/5 px-2 py-1 text-[11px] uppercase tracking-wider text-signal">Enterprise</span></div><nav className="flex items-center gap-4"><Link href="/guardian" className="mono text-[11px] uppercase text-ink-faint hover:text-ink">Guardian</Link><Link href="/agency" className="mono text-[11px] uppercase text-ink-faint hover:text-ink">Agency</Link><Link href="/account" className="mono text-[11px] uppercase text-ink-faint hover:text-ink">Account</Link><LogoutButton/></nav></div></header><main className="mx-auto max-w-[1500px] px-5 py-7 md:px-8 md:py-10"><EnterpriseConsole initial={overview} organizationName={organizationName}/></main></div>; }
