import { createHmac } from "node:crypto";
import { recordEnterpriseDelivery } from "@/lib/observability/metrics";
import { decryptEnterpriseSecret } from "./crypto";
import { safeEnterpriseRequest } from "./http";
import { providerPayload, type EnterpriseEventEnvelope, type EnterpriseProvider } from "./providers";
import type { AppendEnterpriseAuditInput, EnterpriseStore } from "./store-model";
import type { EnterpriseDelivery, EnterpriseIntegration, EnterpriseTicketLink } from "./types";

type Config = Record<string, string>;
function request(integration: EnterpriseIntegration, config: Config, event: EnterpriseEventEnvelope): { url: string; body: string; headers: Record<string, string> } {
  const payload = providerPayload(integration.provider as EnterpriseProvider, event), headers: Record<string, string> = { "content-type": "application/json", "x-outside-event-id": event.id, "idempotency-key": event.id };
  if (integration.provider === "pagerduty") (payload as Record<string, unknown>).routing_key = config.routingKey;
  let body = JSON.stringify(integration.provider === "microsoft_sentinel" ? [payload] : payload), url = config.url!;
  if (integration.provider === "splunk") headers.authorization = `Splunk ${config.hecToken}`;
  else if (integration.provider === "elastic") headers.authorization = `ApiKey ${config.apiKey}`;
  else if (integration.provider === "qradar") headers["sec"] = config.token!;
  else if (["chronicle", "cortex_xsoar"].includes(integration.provider)) headers.authorization = `Bearer ${config.token ?? config.apiKey}`;
  else if (integration.provider === "servicenow") { headers.authorization = `Basic ${Buffer.from(`${config.username}:${config.password}`).toString("base64")}`; body = JSON.stringify({ short_description: event.title, description: event.description, correlation_id: event.id, impact: event.severity === "critical" ? "1" : event.severity === "high" ? "2" : "3", urgency: event.severity === "critical" ? "1" : "2", u_outside_evidence: JSON.stringify(event.evidence) }); }
  else if (integration.provider === "freshservice") { headers.authorization = `Basic ${Buffer.from(`${config.apiKey}:X`).toString("base64")}`; body = JSON.stringify({ subject: event.title, description: event.description, status: 2, priority: event.severity === "critical" ? 4 : event.severity === "high" ? 3 : 2, custom_fields: { outside_event_id: event.id } }); }
  else if (integration.provider === "jira_service_management") { headers.authorization = `Basic ${Buffer.from(`${config.email}:${config.apiToken}`).toString("base64")}`; body = JSON.stringify({ fields: { project: { key: config.projectKey }, summary: event.title.slice(0, 250), description: event.description, issuetype: { name: "Task" }, labels: ["outside-enterprise", `outside-${event.severity}`] } }); }
  else if (integration.provider === "opsgenie") { headers.authorization = `GenieKey ${config.apiKey}`; body = JSON.stringify({ message: event.title.slice(0, 130), alias: event.id, description: event.description, priority: event.severity === "critical" ? "P1" : event.severity === "high" ? "P2" : "P3", details: event.evidence }); }
  else if (integration.provider === "webhook") { const timestamp = Math.floor(Date.now() / 1000).toString(); headers["x-outside-timestamp"] = timestamp; headers["x-outside-signature"] = `v1=${createHmac("sha256", config.signingSecret!).update(`${timestamp}.${body}`).digest("hex")}`; headers["x-outside-schema"] = "com.outside.enterprise.event/v1"; }
  else if (integration.provider === "microsoft_sentinel") { const date = new Date().toUTCString(), path = new URL(url).pathname, signatureInput = `POST\n${Buffer.byteLength(body)}\napplication/json\nx-ms-date:${date}\n${path}`, signature = createHmac("sha256", Buffer.from(config.sharedKey!, "base64")).update(signatureInput).digest("base64"); headers["x-ms-date"] = date; headers["log-type"] = config.logType!; headers.authorization = `SharedKey ${config.customerId}:${signature}`; }
  return { url, body, headers };
}

export async function queueEnterpriseEvent(store: EnterpriseStore, workspaceId: string, event: EnterpriseEventEnvelope, audit: Omit<AppendEnterpriseAuditInput, "workspaceId" | "resourceId">): Promise<number> { const integrations = (await store.list<EnterpriseIntegration>(workspaceId, "integrations")).filter((item) => item.enabled && (!item.eventTypes.length || item.eventTypes.includes(event.type)) && (!item.severities.length || item.severities.includes(event.severity))); return store.enqueueEventAudited({ workspaceId, integrations: integrations.map((integration) => ({ id: integration.id, idempotencyKey: `enterprise:${workspaceId}:${integration.id}:${event.id}` })), eventId: event.id, payload: event as unknown as Record<string, unknown> }, audit); }

function ticketIdentity(provider: string, responseBody: string): { id: string; url: string | null; status: string } | null { try { const body = JSON.parse(responseBody) as Record<string, unknown>, result = body.result && typeof body.result === "object" ? body.result as Record<string, unknown> : body; const id = String(result.sys_id ?? result.id ?? result.key ?? result.incident_key ?? ""); if (!id) return null; return { id, url: typeof result.url === "string" ? result.url : null, status: String(result.status ?? "open") }; } catch { return provider === "pagerduty" ? { id: "event-accepted", url: null, status: "triggered" } : null; } }

export async function deliverEnterpriseBatch(store: EnterpriseStore, limit = 25): Promise<{ delivered: number; failed: number }> { const jobs = await store.claimDeliveries(new Date(), limit, 60_000); let delivered = 0, failed = 0; for (const job of jobs) { const started = Date.now(); let integration: EnterpriseIntegration | undefined; try { integration = (await store.list<EnterpriseIntegration>(job.workspaceId, "integrations")).find((item) => item.id === job.integrationId && item.enabled); if (!integration) throw new Error("Enterprise integration is disabled or unavailable."); const event = job.payload as unknown as EnterpriseEventEnvelope, config = decryptEnterpriseSecret<Config>(integration.configEncrypted), outgoing = request(integration, config, event), response = await safeEnterpriseRequest(outgoing.url, { method: "POST", body: outgoing.body, headers: outgoing.headers, maxBodyBytes: 256_000, timeoutMs: 12_000 }); if (response.status < 200 || response.status >= 300) throw new Error(`Integration returned HTTP ${response.status}.`); await store.finishDelivery(job.workspaceId, job.id, job.leaseId!, { delivered: true }); await store.update<EnterpriseIntegration>(job.workspaceId, "integrations", integration.id, { status: "healthy", lastDeliveryAt: new Date().toISOString(), lastError: null }); if (integration.category === "ticketing") { const ticket = ticketIdentity(integration.provider, response.body); if (ticket) await upsertTicket(store, job, integration, event, ticket); } recordEnterpriseDelivery(integration.provider, integration.category, "delivered", Date.now() - started, Date.now() - new Date(job.createdAt!).getTime()); delivered += 1; } catch (error) { await store.finishDelivery(job.workspaceId, job.id, job.leaseId!, { delivered: false, error: (error as Error).message }); if (integration) { await store.update<EnterpriseIntegration>(job.workspaceId, "integrations", integration.id, { status: "degraded", lastError: (error as Error).message.slice(0, 1000) }); recordEnterpriseDelivery(integration.provider, integration.category, "failed", Date.now() - started, Date.now() - new Date(job.createdAt!).getTime()); } failed += 1; } } return { delivered, failed }; }
async function upsertTicket(store: EnterpriseStore, job: EnterpriseDelivery, integration: EnterpriseIntegration, event: EnterpriseEventEnvelope, ticket: { id: string; url: string | null; status: string }) { const findingId = event.resource.type === "finding" ? event.resource.id : event.id, existing = (await store.list<EnterpriseTicketLink>(job.workspaceId, "tickets")).find((item) => item.provider === integration.provider && item.findingId === findingId); if (existing) await store.update<EnterpriseTicketLink>(job.workspaceId, "tickets", existing.id, { externalId: ticket.id, externalUrl: ticket.url, status: ticket.status, syncVersion: existing.syncVersion + 1, lastSyncedAt: new Date().toISOString() }); else await store.create<EnterpriseTicketLink>(job.workspaceId, "tickets", { provider: integration.provider, findingId, externalId: ticket.id, externalUrl: ticket.url, status: ticket.status, syncVersion: 1, lastSyncedAt: new Date().toISOString(), metadata: { integrationId: integration.id } }); }
