import { randomUUID } from "node:crypto";
import { auditHash, canonicalAuditDetail } from "./audit";
import { SYSTEM_ROLES, type EnterpriseApiToken, type EnterpriseAuditEvent, type EnterpriseDelivery, type EnterpriseIdentityProvider, type EnterpriseOverview, type EnterpriseRecord, type EnterpriseResourceKind, type EnterpriseWorkspace } from "./types";
import type { AppendEnterpriseAuditInput, EnterpriseStore } from "./store-model";

const iso = () => new Date().toISOString();
const clone = <T>(value: T): T => structuredClone(value);

export class InMemoryEnterpriseStore implements EnterpriseStore {
  readonly durable = false;
  private workspaces = new Map<string, EnterpriseWorkspace>();
  private records = new Map<EnterpriseResourceKind, Map<string, EnterpriseRecord>>();
  private audit = new Map<string, EnterpriseAuditEvent[]>();
  constructor() { for (const kind of ["identityProviders", "directoryUsers", "directoryGroups", "roles", "bindings", "units", "ownership", "policies", "approvals", "exceptions", "apiTokens", "integrations", "deliveries", "tickets", "exports", "flags"] as EnterpriseResourceKind[]) this.records.set(kind, new Map()); }
  async workspace(id: string) { return clone(this.workspaces.get(id) ?? null); }
  async allWorkspaces(options?: { limit?: number; afterId?: string }) {
    const rows = [...this.workspaces.values()].filter((item) => !options?.afterId || item.id > options.afterId).sort((left, right) => left.id.localeCompare(right.id));
    return clone(options?.limit ? rows.slice(0, options.limit) : rows);
  }
  async workspaceByOrg(orgId: string) { return clone([...this.workspaces.values()].find((item) => item.orgId === orgId) ?? null); }
  async identityProvider(id: string) { return clone(this.records.get("identityProviders")!.get(id) as EnterpriseIdentityProvider | undefined ?? null); }
  async identityProviderByDomain(domain: string) { const normalized = domain.toLowerCase(); return clone([...this.records.get("identityProviders")!.values()].find((item) => Array.isArray(item.domains) && item.domains.includes(normalized)) as EnterpriseIdentityProvider | undefined ?? null); }
  async integration(id: string) { return clone(this.records.get("integrations")!.get(id) as import("./types").EnterpriseIntegration | undefined ?? null); }
  async provision(input: { orgId: string; ownerUserId: string; licensedSeats?: number; dataRegion?: EnterpriseWorkspace["dataRegion"]; expiresAt?: string | null }) {
    const existing = await this.workspaceByOrg(input.orgId); if (existing) return existing;
    const now = iso(); const workspace: EnterpriseWorkspace = { id: randomUUID(), orgId: input.orgId, licenseStatus: "trial", licensedSeats: input.licensedSeats ?? 25, features: ["sso", "scim", "advanced_rbac", "audit_exports", "hierarchy", "ownership", "governance", "api", "integrations", "reporting", "data_controls"], dataRegion: input.dataRegion ?? "eu", retention: { auditDays: 2555, exportDays: 365 }, provisioningMode: "manual", expiresAt: input.expiresAt ?? null, createdAt: now, updatedAt: now };
    this.workspaces.set(workspace.id, workspace);
    let ownerRoleId = "";
    for (const role of SYSTEM_ROLES) { const created = await this.create<EnterpriseRecord>(workspace.id, "roles", role as never); if (role.name === "Enterprise Owner") ownerRoleId = created.id; }
    await this.create(workspace.id, "bindings", { roleId: ownerRoleId, principalType: "user", principalId: input.ownerUserId, scopeType: "organization", scopeId: null, conditions: {}, createdBy: input.ownerUserId } as never);
    await this.appendAudit({ workspaceId: workspace.id, actorType: "user", actorId: input.ownerUserId, action: "enterprise.workspace.provisioned", resourceType: "workspace", resourceId: workspace.id, requestId: null, ipHash: null, detail: { dataRegion: workspace.dataRegion, licensedSeats: workspace.licensedSeats } });
    return clone(workspace);
  }
  async updateWorkspace(id: string, patch: Partial<EnterpriseWorkspace>) { const current = this.workspaces.get(id); if (!current) return null; const next = { ...current, ...patch, id: current.id, orgId: current.orgId, updatedAt: iso() }; this.workspaces.set(id, next); return clone(next); }
  async updateWorkspaceAudited(id: string, patch: Partial<EnterpriseWorkspace>, audit: Omit<AppendEnterpriseAuditInput, "workspaceId" | "resourceId">) { const item = await this.updateWorkspace(id, patch); if (item) await this.appendAudit({ ...audit, workspaceId: id, resourceId: id }); return item; }
  async list<T extends EnterpriseRecord>(workspaceId: string, kind: EnterpriseResourceKind, options?: { limit?: number; afterId?: string }): Promise<T[]> { const rows = [...this.records.get(kind)!.values()].filter((item) => item.workspaceId === workspaceId && (!options?.afterId || item.id > options.afterId)).sort((left, right) => left.id.localeCompare(right.id)); return clone(options?.limit ? rows.slice(0, options.limit) : rows) as T[]; }
  async resource<T extends EnterpriseRecord>(workspaceId: string, kind: EnterpriseResourceKind, id: string): Promise<T | null> { const item = this.records.get(kind)!.get(id); return item?.workspaceId === workspaceId ? clone(item) as T : null; }
  async create<T extends EnterpriseRecord>(workspaceId: string, kind: EnterpriseResourceKind, input: Omit<T, "id" | "workspaceId" | "createdAt" | "updatedAt">): Promise<T> { const now = iso(); const value = { ...input, id: randomUUID(), workspaceId, createdAt: now, updatedAt: now } as T; this.records.get(kind)!.set(value.id, value); return clone(value); }
  async createAudited<T extends EnterpriseRecord>(workspaceId: string, kind: EnterpriseResourceKind, input: Omit<T, "id" | "workspaceId" | "createdAt" | "updatedAt">, audit: Omit<AppendEnterpriseAuditInput, "workspaceId" | "resourceId">): Promise<T> { const item = await this.create<T>(workspaceId, kind, input); await this.appendAudit({ ...audit, workspaceId, resourceId: item.id }); return item; }
  async update<T extends EnterpriseRecord>(workspaceId: string, kind: EnterpriseResourceKind, id: string, patch: Partial<T>): Promise<T | null> { const current = this.records.get(kind)!.get(id) as T | undefined; if (!current || current.workspaceId !== workspaceId) return null; const next = { ...current, ...patch, id, workspaceId, updatedAt: iso() }; this.records.get(kind)!.set(id, next); return clone(next); }
  async updateAudited<T extends EnterpriseRecord>(workspaceId: string, kind: EnterpriseResourceKind, id: string, patch: Partial<T>, audit: Omit<AppendEnterpriseAuditInput, "workspaceId" | "resourceId">): Promise<T | null> { const item = await this.update<T>(workspaceId, kind, id, patch); if (item) await this.appendAudit({ ...audit, workspaceId, resourceId: id }); return item; }
  async remove(workspaceId: string, kind: EnterpriseResourceKind, id: string) { const value = this.records.get(kind)!.get(id); return !!value && value.workspaceId === workspaceId && this.records.get(kind)!.delete(id); }
  async removeAudited(workspaceId: string, kind: EnterpriseResourceKind, id: string, audit: Omit<AppendEnterpriseAuditInput, "workspaceId" | "resourceId">) { const removed = await this.remove(workspaceId, kind, id); if (removed) await this.appendAudit({ ...audit, workspaceId, resourceId: id }); return removed; }
  async authenticateApiToken(hash: string, now: Date) { const token = [...this.records.get("apiTokens")!.values()].find((item) => item.secretHash === hash) as EnterpriseApiToken | undefined; if (!token || token.revokedAt || (token.expiresAt && new Date(token.expiresAt) <= now)) return null; token.lastUsedAt = now.toISOString(); return clone(token); }
  async authenticateScimToken(hash: string) { return clone([...this.records.get("identityProviders")!.values()].find((item) => item.scimTokenHash === hash && item.enabled) as EnterpriseIdentityProvider | undefined ?? null); }
  async rotateScimToken(workspaceId: string, id: string, hash: string, prefix: string) { const item = this.records.get("identityProviders")!.get(id) as EnterpriseIdentityProvider | undefined; if (!item || item.workspaceId !== workspaceId) return null; item.scimTokenHash = hash; item.scimTokenPrefix = prefix; return clone(item); }
  async rotateScimTokenAudited(workspaceId: string, id: string, hash: string, prefix: string, audit: Omit<AppendEnterpriseAuditInput, "workspaceId" | "resourceId">) { const item = await this.rotateScimToken(workspaceId, id, hash, prefix); if (item) await this.appendAudit({ ...audit, workspaceId, resourceId: id }); return item; }
  async enqueueDelivery(input: { workspaceId: string; integrationId: string; idempotencyKey: string; eventId: string; payload: Record<string, unknown> }) { const existing = [...this.records.get("deliveries")!.values()].find((item) => item.idempotencyKey === input.idempotencyKey) as EnterpriseDelivery | undefined; if (existing) return clone(existing); return this.create<EnterpriseDelivery>(input.workspaceId, "deliveries", { integrationId: input.integrationId, idempotencyKey: input.idempotencyKey, eventId: input.eventId, payload: input.payload, status: "pending", attempts: 0, nextAttemptAt: iso(), leaseId: null, leasedUntil: null, lastError: null, deliveredAt: null }); }
  async enqueueEventAudited(input: { workspaceId: string; integrations: Array<{ id: string; idempotencyKey: string }>; eventId: string; payload: Record<string, unknown> }, audit: Omit<AppendEnterpriseAuditInput, "workspaceId" | "resourceId">) { for (const integration of input.integrations) await this.enqueueDelivery({ workspaceId: input.workspaceId, integrationId: integration.id, idempotencyKey: integration.idempotencyKey, eventId: input.eventId, payload: input.payload }); await this.appendAudit({ ...audit, workspaceId: input.workspaceId, resourceId: null, detail: { ...audit.detail, integrations: input.integrations.length } }); return input.integrations.length; }
  async claimDeliveries(now: Date, limit: number, leaseMs: number) { const items = [...this.records.get("deliveries")!.values()].filter((item) => ["pending", "processing"].includes(String(item.status)) && new Date(String(item.nextAttemptAt)) <= now && (!item.leasedUntil || new Date(String(item.leasedUntil)) <= now)).slice(0, limit) as EnterpriseDelivery[]; return items.map((item) => { item.status = "processing"; item.attempts += 1; item.leaseId = randomUUID(); item.leasedUntil = new Date(now.getTime() + leaseMs).toISOString(); return clone(item); }); }
  async finishDelivery(workspaceId: string, id: string, leaseId: string, result: { delivered: boolean; error?: string }) { const item = this.records.get("deliveries")!.get(id) as EnterpriseDelivery | undefined; if (!item || item.workspaceId !== workspaceId || item.leaseId !== leaseId) return false; item.leaseId = null; item.leasedUntil = null; if (result.delivered) { item.status = "delivered"; item.deliveredAt = iso(); item.lastError = null; } else { item.status = item.attempts >= 8 ? "dead_letter" : "pending"; item.lastError = result.error?.slice(0, 1000) ?? "Delivery failed"; item.nextAttemptAt = new Date(Date.now() + Math.min(3_600_000, 2 ** item.attempts * 1000)).toISOString(); } return true; }
  async updateTicketInbound(workspaceId: string, id: string, expectedVersion: number, patch: Partial<import("./types").EnterpriseTicketLink>) { const item = this.records.get("tickets")!.get(id) as import("./types").EnterpriseTicketLink | undefined; if (!item || item.workspaceId !== workspaceId || item.syncVersion !== expectedVersion) return null; return this.update(workspaceId, "tickets", id, patch); }
  async updateTicketInboundAudited(workspaceId: string, id: string, expectedVersion: number, patch: Partial<import("./types").EnterpriseTicketLink>, audit: Omit<AppendEnterpriseAuditInput, "workspaceId" | "resourceId">) { const item = await this.updateTicketInbound(workspaceId, id, expectedVersion, patch); if (item) await this.appendAudit({ ...audit, workspaceId, resourceId: id }); return item; }
  async purgeRetention(workspaceId: string, cutoffs: { deliveries: Date; tickets: Date }) { let deliveries = 0, tickets = 0; for (const [id, row] of this.records.get("deliveries")!) if (row.workspaceId === workspaceId && ["delivered", "dead_letter"].includes(String(row.status)) && new Date(String(row.deliveredAt ?? row.createdAt)) < cutoffs.deliveries && this.records.get("deliveries")!.delete(id)) deliveries += 1; for (const [id, row] of this.records.get("tickets")!) if (row.workspaceId === workspaceId && new Date(String(row.lastSyncedAt)) < cutoffs.tickets && this.records.get("tickets")!.delete(id)) tickets += 1; return { deliveries, tickets }; }
  async appendAudit(input: AppendEnterpriseAuditInput) { const events = this.audit.get(input.workspaceId) ?? []; const previous = events.at(-1), createdAt = iso(); const base = { sequence: String(events.length + 1), actorType: input.actorType, actorId: input.actorId, action: input.action, resourceType: input.resourceType, resourceId: input.resourceId, requestId: input.requestId, ipHash: input.ipHash, detail: canonicalAuditDetail(input.detail), previousHash: previous?.hash ?? "GENESIS", createdAt }; const event: EnterpriseAuditEvent = { ...base, id: randomUUID(), workspaceId: input.workspaceId, hash: auditHash(base) }; events.push(event); this.audit.set(input.workspaceId, events); return clone(event); }
  async auditEvents(workspaceId: string, limit = 250, afterSequence?: string) { return clone((this.audit.get(workspaceId) ?? []).filter((event) => !afterSequence || BigInt(event.sequence) > BigInt(afterSequence)).slice(-Math.min(limit, 5000))); }
  async overview(workspaceId: string): Promise<EnterpriseOverview | null> { const workspace = await this.workspace(workspaceId); if (!workspace) return null; const counts = {} as EnterpriseOverview["counts"]; for (const kind of this.records.keys()) counts[kind] = (await this.list(workspaceId, kind)).length; const events = await this.auditEvents(workspaceId); counts.audit = events.length; const identityProviders = (await this.list<EnterpriseIdentityProvider>(workspaceId, "identityProviders")).map(({ configEncrypted: _config, scimTokenHash: _hash, ...item }) => item); const integrations = (await this.list<Record<string, unknown> & EnterpriseRecord>(workspaceId, "integrations")).map(({ configEncrypted: _config, ...item }) => item) as EnterpriseOverview["integrations"]; return { workspace, counts, identityProviders, pendingApprovals: (await this.list(workspaceId, "approvals")).filter((item) => item.status === "pending") as EnterpriseOverview["pendingApprovals"], expiringExceptions: (await this.list(workspaceId, "exceptions")).filter((item) => item.status === "approved") as EnterpriseOverview["expiringExceptions"], integrations, flags: await this.list(workspaceId, "flags"), auditHead: events.length ? { sequence: events.at(-1)!.sequence, hash: events.at(-1)!.hash } : null }; }
}
