import { buildEnterpriseReport } from "./reporting";
import { workspaceInRegion } from "./residency";
import type { EnterpriseStore } from "./store-model";
import type { EnterpriseExport, EnterpriseIntegration, EnterpriseWorkspace } from "./types";

const daysAgo = (days: number, now: Date) => new Date(now.getTime() - days * 86_400_000);
const retention = (value: unknown, fallback: number, minimum: number) => Math.max(minimum, Math.min(3650, Number(value) || fallback));

interface FleetOptions { limit?: number; afterId?: string }
interface FleetPage { workspaces: EnterpriseWorkspace[]; nextCursor: string | null }

async function fleetPage(store: EnterpriseStore, options: FleetOptions): Promise<FleetPage> {
  const limit = Math.max(1, Math.min(500, options.limit ?? 100));
  const rows = await store.allWorkspaces({ limit: limit + 1, afterId: options.afterId });
  return {
    workspaces: rows.slice(0, limit).filter(workspaceInRegion),
    nextCursor: rows.length > limit ? rows[limit - 1]!.id : null,
  };
}

export async function enforceEnterpriseRetention(store: EnterpriseStore, now = new Date(), options: FleetOptions = {}): Promise<{ workspaces: number; removed: Record<string, number>; immutableAuditEvents: number; nextCursor: string | null }> {
  const removed = { deliveries: 0, tickets: 0 };
  const page = await fleetPage(store, options);
  let immutableAuditEvents = 0;
  for (const workspace of page.workspaces) {
    const result = await store.purgeRetention(workspace.id, {
      deliveries: daysAgo(retention(workspace.retention.integrationDays, 90, 30), now),
      tickets: daysAgo(retention(workspace.retention.ticketDays, 730, 30), now),
    });
    removed.deliveries += result.deliveries;
    removed.tickets += result.tickets;
    immutableAuditEvents += Number((await store.overview(workspace.id))?.counts.audit ?? 0);
  }
  return { workspaces: page.workspaces.length, removed, immutableAuditEvents, nextCursor: page.nextCursor };
}

function nextRun(schedule: string, from: Date): Date {
  const date = new Date(from);
  if (schedule === "daily") date.setUTCDate(date.getUTCDate() + 1);
  else if (schedule === "weekly") date.setUTCDate(date.getUTCDate() + 7);
  else date.setUTCMonth(date.getUTCMonth() + 1);
  return date;
}

export async function runScheduledEnterpriseExports(store: EnterpriseStore, now = new Date(), options: FleetOptions = {}): Promise<{ queued: number; failed: number; nextCursor: string | null }> {
  let queued = 0;
  let failed = 0;
  const page = await fleetPage(store, options);
  for (const workspace of page.workspaces) {
    const due = (await store.list<EnterpriseExport>(workspace.id, "exports", { limit: 1000 })).filter((item) => item.enabled && item.schedule && item.nextRunAt && new Date(item.nextRunAt) <= now);
    if (!due.length) continue;
    const [overview, integrations] = await Promise.all([
      store.overview(workspace.id),
      store.list<EnterpriseIntegration>(workspace.id, "integrations", { limit: 1000 }),
    ]);
    if (!overview) continue;
    for (const job of due) {
      const scheduledFor = job.nextRunAt!;
      const integration = integrations.find((item) => item.id === job.destinationIntegrationId && item.enabled);
      try {
        if (!integration) throw new Error("Scheduled export destination is unavailable.");
        const audit = await store.auditEvents(workspace.id, job.kind === "audit" ? 5000 : 500);
        const report = await buildEnterpriseReport(overview, audit, job.kind as "executive" | "compliance" | "audit");
        await store.enqueueDelivery({
          workspaceId: workspace.id,
          integrationId: integration.id,
          idempotencyKey: `enterprise:export:${job.id}:${scheduledFor}`,
          eventId: `export:${job.id}:${scheduledFor}`,
          payload: { id: `export:${job.id}:${scheduledFor}`, occurredAt: now.toISOString(), organizationId: workspace.orgId, type: "enterprise.export.ready", severity: "info", title: `${job.name} scheduled export`, description: `Deterministic ${job.kind} export generated by OUTSIDE.`, resource: { type: "export", id: job.id, name: job.name }, evidence: { format: job.format, report } },
        });
        await store.update<EnterpriseExport>(workspace.id, "exports", job.id, { lastRunAt: now.toISOString(), lastStatus: "queued", nextRunAt: nextRun(job.schedule!, new Date(scheduledFor)).toISOString() });
        queued += 1;
      } catch (error) {
        await store.update<EnterpriseExport>(workspace.id, "exports", job.id, { lastRunAt: now.toISOString(), lastStatus: `failed: ${(error as Error).message}`.slice(0, 500), nextRunAt: nextRun(job.schedule!, new Date(scheduledFor)).toISOString() });
        failed += 1;
      }
    }
  }
  return { queued, failed, nextCursor: page.nextCursor };
}
