import { getGuardianStore } from "@/lib/guardian/store";
import { csvCell } from "@/lib/export/csv";
import type { GuardianOverview } from "@/lib/guardian/types";
import { verifyAuditChain } from "./audit";
import type { EnterpriseAuditEvent, EnterpriseOverview } from "./types";

export interface ComplianceControl { id: string; framework: string; title: string; status: "evidenced" | "partial" | "not_evidenced"; evidence: string[]; note: string; }
export interface EnterpriseReportData { schema: "com.outside.enterprise.report/v1"; kind: "executive" | "compliance" | "audit"; generatedAt: string; organizationId: string; dataRegion: string; summary: { posture: number | null; assets: number; criticalRecommendations: number; identityProviders: number; integrations: number; pendingApprovals: number; riskExceptions: number }; recommendations: Array<{ id: string; title: string; priority: string; why: string; affectedAssets: string[] }>; controls: ComplianceControl[]; auditIntegrity: ReturnType<typeof verifyAuditChain>; audit: EnterpriseAuditEvent[]; disclaimer: string; }
const controls = (overview: EnterpriseOverview, guardian: GuardianOverview, audit: EnterpriseAuditEvent[]): ComplianceControl[] => {
  const hasSso = overview.identityProviders.some((item) => item.enabled), hasScim = overview.identityProviders.some((item) => item.scimTokenPrefix), auditOk = verifyAuditChain(audit).valid, hasIntegrations = overview.integrations.some((item) => item.enabled), retention = Number(overview.workspace.retention.auditDays ?? 0);
  return [
    { id: "CC6.1", framework: "SOC 2", title: "Logical access controls", status: hasSso ? "evidenced" : "partial", evidence: hasSso ? overview.identityProviders.filter((item) => item.enabled).map((item) => `Configured ${item.protocol.toUpperCase()} provider ${item.name}`) : [], note: "Configuration evidence only; operating effectiveness requires independent testing." },
    { id: "A.5.16", framework: "ISO 27001", title: "Identity management", status: hasScim ? "evidenced" : hasSso ? "partial" : "not_evidenced", evidence: hasScim ? ["SCIM lifecycle provisioning is configured"] : [], note: "OUTSIDE does not assert certification or control effectiveness." },
    { id: "CC7.2", framework: "SOC 2", title: "Security event monitoring", status: guardian.targets.length && hasIntegrations ? "evidenced" : guardian.targets.length ? "partial" : "not_evidenced", evidence: [`${guardian.targets.length} monitored target(s)`, `${overview.integrations.filter((item) => item.enabled).length} enabled integration(s)`], note: "Derived from deterministic OUTSIDE monitoring state." },
    { id: "A.8.15", framework: "ISO 27001", title: "Logging", status: auditOk && retention >= 365 ? "evidenced" : auditOk ? "partial" : "not_evidenced", evidence: auditOk ? [`Hash chain verified across ${audit.length} loaded event(s)`, `Configured audit retention: ${retention || "platform minimum"} days`] : [], note: "Hash-chain integrity is verified at report generation." },
    { id: "NIS2-21.2", framework: "NIS2", title: "Risk analysis and incident handling", status: guardian.recommendations.length ? "evidenced" : "partial", evidence: [`${guardian.recommendations.length} deterministic recommendation(s)`, `${overview.pendingApprovals.length} pending approval(s)`], note: "Evidence supports review; it is not a legal compliance determination." },
    { id: "DORA-10", framework: "DORA", title: "Detection and response", status: hasIntegrations && guardian.recentEvents.length ? "evidenced" : "partial", evidence: [`${guardian.recentEvents.length} correlated external change event(s)`], note: "External-surface telemetry is one input into a wider ICT risk program." },
  ];
};
export async function buildEnterpriseReport(overview: EnterpriseOverview, audit: EnterpriseAuditEvent[], kind: EnterpriseReportData["kind"]): Promise<EnterpriseReportData> { const guardian = await getGuardianStore().then((store) => store.overview(overview.workspace.orgId)), latest = guardian.targets.map((item) => item.latest.exposureScore), recommendations = guardian.recommendations.filter((item) => item.status === "open"); return { schema: "com.outside.enterprise.report/v1", kind, generatedAt: new Date().toISOString(), organizationId: overview.workspace.orgId, dataRegion: overview.workspace.dataRegion, summary: { posture: latest.length ? Math.round(latest.reduce((sum, value) => sum + value, 0) / latest.length) : null, assets: guardian.targets.reduce((sum, item) => sum + item.latest.metrics.assets, 0), criticalRecommendations: recommendations.filter((item) => ["critical", "high"].includes(item.priority)).length, identityProviders: overview.identityProviders.filter((item) => item.enabled).length, integrations: overview.integrations.filter((item) => item.enabled).length, pendingApprovals: overview.pendingApprovals.length, riskExceptions: overview.expiringExceptions.length }, recommendations: recommendations.slice(0, 100).map((item) => ({ id: item.id, title: item.title, priority: item.priority, why: item.why, affectedAssets: item.affectedAssets })), controls: controls(overview, guardian, audit), auditIntegrity: verifyAuditChain(audit), audit: kind === "audit" ? audit : audit.slice(-25), disclaimer: "This report summarizes deterministic observations and configured controls. It does not assert vulnerability, certification, or regulatory compliance." }; }
export function reportCsv(report: EnterpriseReportData): string { return [["framework", "control", "title", "status", "evidence", "note"].join(","), ...report.controls.map((item) => [item.framework, item.id, item.title, item.status, item.evidence.join("; "), item.note].map(csvCell).join(","))].join("\r\n"); }
