import { ENTERPRISE_PERMISSIONS, type EnterprisePermission, type EnterpriseResourceKind } from "./types";

const text = (value: unknown, max = 200) => typeof value === "string" ? value.trim().slice(0, max) : "";
const list = (value: unknown, max = 100) => Array.isArray(value) ? [...new Set(value.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter(Boolean))].slice(0, max) : [];
const object = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const oneOf = <T extends string>(value: unknown, values: readonly T[], fallback?: T): T => values.includes(value as T) ? value as T : fallback ?? (() => { throw new Error(`Expected one of: ${values.join(", ")}.`); })();
const date = (value: unknown, required = false): string | null => { if (!value && !required) return null; const parsed = new Date(String(value)); if (!Number.isFinite(parsed.getTime())) throw new Error("A valid date is required."); return parsed.toISOString(); };

export const RESOURCE_PERMISSION: Record<EnterpriseResourceKind, EnterprisePermission> = {
  identityProviders: "identity:manage", directoryUsers: "scim:manage", directoryGroups: "scim:manage", roles: "roles:manage", bindings: "roles:manage", units: "hierarchy:manage", ownership: "ownership:manage", policies: "policies:manage", approvals: "approvals:request", exceptions: "exceptions:manage", apiTokens: "tokens:manage", integrations: "integrations:manage", deliveries: "integrations:manage", tickets: "tickets:manage", exports: "reports:manage", flags: "flags:manage",
};

export function sanitizeResource(kind: EnterpriseResourceKind, value: unknown, actorId: string): Record<string, unknown> {
  const body = object(value);
  switch (kind) {
    case "roles": { const name = text(body.name, 80); if (name.length < 2) throw new Error("Role name is required."); const permissions = list(body.permissions).filter((item): item is EnterprisePermission => ENTERPRISE_PERMISSIONS.includes(item as EnterprisePermission)); if (!permissions.length) throw new Error("At least one valid permission is required."); return { name, description: text(body.description, 500) || null, permissions, system: false }; }
    case "bindings": { const roleId = text(body.roleId, 120), principalId = text(body.principalId, 180); if (!roleId || !principalId) throw new Error("Role and principal are required."); return { roleId, principalType: oneOf(body.principalType, ["user", "group", "service"]), principalId, scopeType: oneOf(body.scopeType, ["organization", "department", "asset", "risk"], "organization"), scopeId: text(body.scopeId, 180) || null, conditions: object(body.conditions), createdBy: actorId }; }
    case "units": { const name = text(body.name, 120), path = text(body.path, 500); if (!name || !/^\/[a-z0-9][a-z0-9/_-]*$/i.test(path) || path.includes("//") || path.includes("..")) throw new Error("A name and canonical hierarchy path are required."); return { parentId: text(body.parentId, 120) || null, kind: oneOf(body.kind, ["organization", "business_unit", "department", "team"], "department"), name, externalId: text(body.externalId, 180) || null, managerId: text(body.managerId, 180) || null, path, metadata: object(body.metadata) }; }
    case "ownership": { const subjectId = text(body.subjectId, 240), ownerId = text(body.ownerId, 180); if (!subjectId || !ownerId) throw new Error("Subject and owner are required."); return { subjectType: oneOf(body.subjectType, ["asset", "risk", "finding", "target"]), subjectId, ownerType: oneOf(body.ownerType, ["user", "group", "department"]), ownerId, role: oneOf(body.role, ["accountable", "responsible", "consulted", "informed"], "accountable"), source: "manual", createdBy: actorId }; }
    case "policies": { const name = text(body.name, 120), document = object(body.document); if (!name || !Object.keys(document).length || JSON.stringify(document).length > 50_000) throw new Error("A non-empty policy document under 50 KB is required."); return { kind: oneOf(body.kind, ["governance", "scoring", "notification", "retention", "approval"]), name, description: text(body.description, 1000) || null, enabled: body.enabled !== false, version: 1, document, createdBy: actorId }; }
    case "approvals": { const subjectId = text(body.subjectId, 240), approverIds = list(body.approverIds, 25); if (!subjectId || !approverIds.length) throw new Error("Approval subject and approvers are required."); return { workflow: text(body.workflow, 100) || "standard", subjectType: text(body.subjectType, 80) || "change", subjectId, status: "pending", requestedBy: actorId, approverIds, decidedBy: null, decisionNote: null, payload: object(body.payload), expiresAt: date(body.expiresAt), decidedAt: null }; }
    case "exceptions": { const subjectId = text(body.subjectId, 240), reason = text(body.reason, 2000), expiresAt = date(body.expiresAt, true)!; if (!subjectId || reason.length < 10 || new Date(expiresAt) <= new Date()) throw new Error("Risk exceptions require a reason and future expiry."); return { subjectType: text(body.subjectType, 80) || "finding", subjectId, policyId: text(body.policyId, 120) || null, reason, compensatingControls: text(body.compensatingControls, 3000) || null, status: "pending", requestedBy: actorId, approvedBy: null, expiresAt }; }
    case "exports": { const name = text(body.name, 120), schedule = body.schedule ? oneOf(body.schedule, ["daily", "weekly", "monthly"]) : null; if (!name) throw new Error("Export name is required."); return { name, kind: oneOf(body.kind, ["executive", "compliance", "audit"], "compliance"), format: oneOf(body.format, ["json", "csv", "ndjson", "cef", "leef", "pdf"], "json"), schedule, destinationIntegrationId: text(body.destinationIntegrationId, 120) || null, filters: object(body.filters), enabled: body.enabled !== false, nextRunAt: schedule ? date(body.nextRunAt) ?? new Date().toISOString() : null, lastRunAt: null, lastStatus: null, createdBy: actorId }; }
    case "flags": { const key = text(body.key, 100).toLowerCase(); if (!/^[a-z][a-z0-9_.-]+$/.test(key)) throw new Error("Feature flag key is invalid."); const rollout = Math.max(0, Math.min(100, Number(body.rollout ?? 100))); return { key, enabled: body.enabled === true, rollout, rules: object(body.rules), updatedBy: actorId }; }
    case "tickets": { const findingId = text(body.findingId, 240), externalId = text(body.externalId, 240); if (!findingId || !externalId) throw new Error("Finding and external ticket IDs are required."); const externalUrl = text(body.externalUrl, 1000); if (externalUrl && new URL(externalUrl).protocol !== "https:") throw new Error("Ticket URL must use HTTPS."); return { provider: text(body.provider, 80), findingId, externalId, externalUrl: externalUrl || null, status: text(body.status, 80) || "open", syncVersion: 1, lastSyncedAt: new Date().toISOString(), metadata: object(body.metadata) }; }
    case "directoryUsers": case "directoryGroups": case "identityProviders": case "apiTokens": case "integrations": case "deliveries": throw new Error(`${kind} must be managed through its dedicated security endpoint.`);
  }
}

export function sanitizePatch(kind: EnterpriseResourceKind, value: unknown, actorId: string): Record<string, unknown> {
  const body = object(value); const output: Record<string, unknown> = {};
  if (kind === "approvals") { const status = oneOf(body.status, ["approved", "rejected", "cancelled"]); output.status = status; output.decidedBy = actorId; output.decisionNote = text(body.decisionNote, 2000) || null; output.decidedAt = new Date().toISOString(); return output; }
  if (kind === "exceptions") { if (body.status !== undefined) output.status = oneOf(body.status, ["approved", "rejected", "revoked"]); if (output.status === "approved") output.approvedBy = actorId; if (body.expiresAt !== undefined) output.expiresAt = date(body.expiresAt, true); return output; }
  if (kind === "flags") { if (typeof body.enabled === "boolean") output.enabled = body.enabled; if (body.rollout !== undefined) output.rollout = Math.max(0, Math.min(100, Number(body.rollout))); output.rules = object(body.rules); output.updatedBy = actorId; return output; }
  if (kind === "roles") { if (body.name !== undefined) output.name = text(body.name, 80); if (body.description !== undefined) output.description = text(body.description, 500) || null; if (body.permissions !== undefined) { const permissions = list(body.permissions).filter((item): item is EnterprisePermission => ENTERPRISE_PERMISSIONS.includes(item as EnterprisePermission)); if (!permissions.length) throw new Error("At least one valid permission is required."); output.permissions = permissions; } return output; }
  if (kind === "policies") { if (body.name !== undefined) output.name = text(body.name, 120); if (body.description !== undefined) output.description = text(body.description, 1000) || null; if (typeof body.enabled === "boolean") output.enabled = body.enabled; if (body.document !== undefined) { const document = object(body.document); if (!Object.keys(document).length || JSON.stringify(document).length > 50_000) throw new Error("A non-empty policy document under 50 KB is required."); output.document = document; } return output; }
  if (kind === "units") { if (body.name !== undefined) { const name = text(body.name, 120); if (!name) throw new Error("Unit name cannot be empty."); output.name = name; } if (body.parentId !== undefined) output.parentId = text(body.parentId, 120) || null; if (body.managerId !== undefined) output.managerId = text(body.managerId, 180) || null; if (body.metadata !== undefined) { const metadata = object(body.metadata); if (JSON.stringify(metadata).length > 20_000) throw new Error("Unit metadata must be under 20 KB."); output.metadata = metadata; } return output; }
  if (kind === "ownership") { if (body.ownerId !== undefined) { const ownerId = text(body.ownerId, 180); if (!ownerId) throw new Error("Owner cannot be empty."); output.ownerId = ownerId; } if (body.role !== undefined) output.role = oneOf(body.role, ["accountable", "responsible", "consulted", "informed"]); return output; }
  if (kind === "exports") { if (body.name !== undefined) { const name = text(body.name, 120); if (!name) throw new Error("Export name cannot be empty."); output.name = name; } if (typeof body.enabled === "boolean") output.enabled = body.enabled; if (body.schedule !== undefined) output.schedule = body.schedule === null ? null : oneOf(body.schedule, ["daily", "weekly", "monthly"]); if (body.filters !== undefined) { const filters = object(body.filters); if (JSON.stringify(filters).length > 20_000) throw new Error("Export filters must be under 20 KB."); output.filters = filters; } return output; }
  throw new Error("This enterprise resource cannot be updated through the generic endpoint.");
}
