"use client";

import { useEffect, useState, type CSSProperties } from "react";
import { useSearchParams } from "next/navigation";

type Portal = {
  workspace: { id: string; name: string; branding: { whiteLabel: boolean; logoUrl: string | null; primaryColor: string; accentColor: string; supportEmail: string | null; emailFooter: string | null } };
  client: { organizationName: string };
  posture: Array<{ target: string; latest: { exposureScore: number; metrics: { assets: number; shadowAssets: number }; checklist: Array<{ code: string; label: string; state: string; whyItMatters: string; recommendedAction: string }> } }>;
  recommendations: Array<{ id: string; title: string; priority: string; why: string; businessImpact: string; suggestedReview: string }>;
  notes: Array<{ id: string; body: string; createdAt: string }>;
  reports: Array<{ id: string; title: string; kind: string; createdAt: string }>;
  recentChanges: Array<{ id: string; title: string; summary: string; observedAt: string }>;
};

export function ClientPortal() {
  const query = useSearchParams(); const [data, setData] = useState<Portal | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/agency/portal?agencyId=${encodeURIComponent(query.get("agencyId") ?? "")}&clientId=${encodeURIComponent(query.get("clientId") ?? "")}`).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); }).catch((reason: Error) => setError(reason.message)); }, [query]);
  if (error) return <div className="panel p-8 text-risk-high">{error}</div>;
  if (!data) return <div className="panel p-8 text-ink-soft">Loading client portal…</div>;
  const brand = data.workspace.branding; const style = { "--agency-primary": brand.primaryColor, "--agency-accent": brand.accentColor } as CSSProperties;
  return <div className="space-y-6" style={style}>
    <section className="panel overflow-hidden p-7" style={{ borderTopColor: brand.primaryColor, borderTopWidth: 3 }}><div className="flex items-center gap-4">{brand.logoUrl && <img src={brand.logoUrl} alt={`${data.workspace.name} logo`} referrerPolicy="no-referrer" decoding="async" className="h-10 max-w-40 object-contain" />}<div><div className="mono text-[10px] uppercase tracking-[.2em]" style={{ color: brand.primaryColor }}>Managed security portal</div><h1 className="mt-2 text-4xl font-semibold text-gradient">{data.client.organizationName}</h1><p className="mt-2 text-sm text-ink-soft">Prepared by {data.workspace.name} · External observations only</p></div></div></section>
    <section className="grid gap-3 md:grid-cols-3">{data.posture.map((posture) => <div key={posture.target} className="panel p-5"><div className="mono text-[10px] text-ink-faint">{posture.target}</div><div className="mono mt-3 text-[9px] uppercase tracking-wider text-ink-faint">Protection posture</div><div className="mt-1 text-4xl font-semibold" style={{ color: brand.primaryColor }}>{posture.latest.exposureScore}<span className="ml-1 text-sm font-normal text-ink-faint">/100</span></div><div className="mt-2 text-xs text-ink-soft">{posture.latest.metrics.assets} assets · {posture.latest.metrics.shadowAssets} shadow</div></div>)}</section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="panel p-5"><div className="mono text-[10px] uppercase text-ink-faint">Shared review items</div><div className="mt-4 space-y-3">{data.recommendations.map((recommendation) => <article key={recommendation.id} className="rounded-xl border border-line p-4"><div className="flex justify-between gap-3"><h2 className="text-sm text-ink">{recommendation.title}</h2><span className="mono text-[9px] uppercase text-risk-high">{recommendation.priority}</span></div><p className="mt-2 text-xs leading-5 text-ink-soft">{recommendation.why}</p><p className="mt-2 text-[11px] text-ink-faint">Business impact: {recommendation.businessImpact}</p><p className="mt-1 text-[11px] text-ink-faint">Review: {recommendation.suggestedReview}</p></article>)}{!data.recommendations.length && <p className="text-sm text-ink-faint">No findings have been shared for review.</p>}</div></div><div className="panel p-5"><div className="mono text-[10px] uppercase text-ink-faint">Recent external changes</div><div className="mt-4 space-y-3">{data.recentChanges.map((event) => <div key={event.id} className="border-b border-line pb-3"><div className="text-xs text-ink">{event.title}</div><div className="mt-1 text-[11px] text-ink-faint">{event.summary}</div></div>)}</div></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="panel p-5"><div className="mono text-[10px] uppercase text-ink-faint">Client reports</div><div className="mt-4 space-y-2">{data.reports.map((report) => <a key={report.id} href={`/api/agency/reports/${report.id}?agencyId=${data.workspace.id}`} className="flex items-center justify-between rounded-lg border border-line p-3 text-sm hover:border-signal/30"><span>{report.title}</span><span className="mono text-[9px] text-ink-faint">PDF · {new Date(report.createdAt).toLocaleDateString()}</span></a>)}{!data.reports.length && <p className="text-sm text-ink-faint">No reports have been published yet.</p>}</div></div><div className="panel p-5"><div className="mono text-[10px] uppercase text-ink-faint">Analyst notes</div><div className="mt-4 space-y-3">{data.notes.map((note) => <div key={note.id} className="rounded-lg border border-line p-3"><p className="text-sm leading-6 text-ink-soft">{note.body}</p><div className="mono mt-2 text-[9px] text-ink-faint">{new Date(note.createdAt).toLocaleString()}</div></div>)}{!data.notes.length && <p className="text-sm text-ink-faint">No shared analyst notes.</p>}</div></div></section>
    {(brand.supportEmail || brand.emailFooter) && <footer className="px-2 text-center text-[11px] text-ink-faint">{brand.emailFooter ?? <>Questions? <a href={`mailto:${brand.supportEmail}`} style={{ color: brand.primaryColor }}>{brand.supportEmail}</a></>}</footer>}
  </div>;
}
