"use client";

import { useState } from "react";
import type { GuardianEvidenceIntelligence, GuardianEvidenceRecord } from "@/lib/guardian/types";

const pct = (value: number) => `${Math.round(value * 100)}%`;
const shortHash = (value: string) => `${value.slice(0, 12)}…${value.slice(-8)}`;

function EvidenceGraph({ data }: { data: GuardianEvidenceIntelligence }) {
  const kinds = ["provider", "observation", "entity", "finding"] as const;
  return <div className="overflow-x-auto rounded-xl border border-line bg-base-950/55 p-4"><div className="grid min-w-[680px] grid-cols-4 gap-4">{kinds.map((kind) => <div key={kind}><div className="mono mb-3 text-[9px] uppercase tracking-wider text-ink-faint">{kind}</div><div className="space-y-2">{data.graph.nodes.filter((node) => node.kind === kind).slice(0, kind === "observation" ? 12 : 8).map((node) => <div key={node.id} title={node.label} className={`truncate rounded-lg border p-2 text-[10px] ${kind === "finding" ? "border-signal/30 bg-signal/10 text-signal" : kind === "observation" ? "border-accent/20 bg-accent/5 text-ink-soft" : "border-line bg-base-900 text-ink-faint"}`}><span className="mr-1.5 text-signal">●</span>{node.label}<div className="mono mt-1 text-[8px] text-ink-faint">{pct(node.confidence)}</div></div>)}</div></div>)}</div><div className="mono mt-4 border-t border-line pt-3 text-[9px] text-ink-faint">{data.graph.edges.length} traceable relationships · providers → observations → resolved entities → finding</div></div>;
}

function ObservationViewer({ records }: { records: GuardianEvidenceRecord[] }) {
  const [selected, setSelected] = useState(records[0]?.id ?? "");
  const [mode, setMode] = useState<"normalized" | "raw">("normalized");
  const record = records.find((item) => item.id === selected) ?? records[0];
  if (!record) return <div className="rounded-lg border border-dashed border-line p-5 text-xs text-ink-faint">No deterministic observations match this finding.</div>;
  const normalized = { subject: record.subject, key: record.normalized.key, value: record.normalized.value, provider: record.provider, method: record.method, observedAt: record.observedAt, discoveryPath: record.discoveryPath, provenance: record.provenance, providerConfidence: record.providerConfidence, evidenceScore: record.evidenceScore, contentHash: record.contentHash };
  return <div className="grid gap-3 lg:grid-cols-[.8fr_1.2fr]"><div className="scroll-thin max-h-72 space-y-1 overflow-y-auto pr-1">{records.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} className={`w-full rounded-lg border p-2.5 text-left ${item.id === record.id ? "border-signal/25 bg-signal/5" : "border-line bg-base-950/50"}`}><div className="flex items-center justify-between gap-2"><span className="mono truncate text-[9px] text-ink-soft">{item.subject}</span><span className="mono text-[8px] text-ink-faint">{Math.round(item.evidenceScore * 100)}</span></div><div className="mt-1 truncate text-[10px] text-ink-faint">{item.summary}</div></button>)}</div><div className="min-w-0 rounded-lg border border-line bg-base-950/70 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex gap-1"><button onClick={() => setMode("normalized")} className={`mono rounded px-2 py-1 text-[8px] uppercase ${mode === "normalized" ? "bg-signal/10 text-signal" : "text-ink-faint"}`}>Normalized</button><button onClick={() => setMode("raw")} className={`mono rounded px-2 py-1 text-[8px] uppercase ${mode === "raw" ? "bg-signal/10 text-signal" : "text-ink-faint"}`}>Raw observation</button></div><span className="mono text-[8px] text-ink-faint">{record.category} · {record.assurance}</span></div><pre className="scroll-thin mt-3 max-h-52 overflow-auto whitespace-pre-wrap break-all text-[10px] leading-5 text-ink-soft">{JSON.stringify(mode === "raw" ? record.rawObservation : normalized, null, 2)}</pre></div></div>;
}

export function EvidenceIntelligencePanel({ orgId, target, findingId, agencyId }: { orgId: string; target: string; findingId: string; agencyId?: string }) {
  const [open, setOpen] = useState(false);
  const [data, setData] = useState<GuardianEvidenceIntelligence | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [section, setSection] = useState<"evidence" | "graph" | "history" | "provenance">("evidence");
  const toggle = async () => {
    setOpen((value) => !value);
    if (data || loading || open) return;
    setLoading(true); setError("");
    const response = await fetch(`/api/guardian/evidence?orgId=${encodeURIComponent(orgId)}&target=${encodeURIComponent(target)}&findingId=${encodeURIComponent(findingId)}${agencyId ? `&agencyId=${encodeURIComponent(agencyId)}` : ""}`, { cache: "no-store" });
    if (response.ok) setData(await response.json() as GuardianEvidenceIntelligence);
    else setError(response.status === 404 ? "No immutable evidence snapshot is available for this finding yet." : "Evidence Intelligence could not be loaded.");
    setLoading(false);
  };
  return <div className="mt-4 border-t border-line pt-4"><button onClick={() => void toggle()} className="mono flex w-full items-center justify-between text-[10px] uppercase tracking-wider text-accent"><span>Evidence Intelligence</span><span>{open ? "Close" : "Explain this finding →"}</span></button>{open && <div className="mt-4">{loading && <div className="animate-pulse rounded-lg border border-line p-5 text-xs text-ink-faint">Correlating immutable observations…</div>}{error && <div className="rounded-lg border border-risk-medium/20 bg-risk-medium/5 p-4 text-xs text-risk-medium">{error}</div>}{data && <div className="space-y-4">
    <section className="rounded-xl border border-signal/20 bg-signal/[.04] p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><div className="mono text-[9px] uppercase tracking-[.16em] text-signal">Why we believe this</div><p className="mt-2 text-xs leading-5 text-ink-soft">{data.whyWeBelieveThis}</p><p className="mt-2 text-[10px] leading-5 text-ink-faint">{data.confidenceExplanation}</p></div><div className="grid grid-cols-2 gap-2 text-center"><div className="rounded-lg bg-base-950/70 px-3 py-2"><div className="text-lg text-signal">{pct(data.confidence)}</div><div className="mono text-[8px] uppercase text-ink-faint">confidence</div></div><div className="rounded-lg bg-base-950/70 px-3 py-2"><div className="text-lg text-accent">{data.evidenceScore}</div><div className="mono text-[8px] uppercase text-ink-faint">evidence score</div></div></div></div><div className="mono mt-3 border-t border-signal/10 pt-3 text-[8px] text-ink-faint">Immutable snapshot · {data.snapshot.scanId} · SHA-256 {shortHash(data.snapshot.contentHash)}</div></section>
    <div className="flex flex-wrap gap-1">{(["evidence", "graph", "history", "provenance"] as const).map((item) => <button key={item} onClick={() => setSection(item)} className={`mono rounded-full border px-2.5 py-1 text-[8px] uppercase ${section === item ? "border-signal/30 bg-signal/10 text-signal" : "border-line text-ink-faint"}`}>{item}</button>)}</div>
    {section === "evidence" && <div className="space-y-3"><ObservationViewer records={data.supportingEvidence}/>{data.correlations.map((item) => <div key={item} className="rounded-lg border border-accent/15 bg-accent/5 p-3 text-[10px] leading-5 text-ink-soft"><span className="mono mr-2 text-[8px] uppercase text-accent">Correlation</span>{item}</div>)}{data.contradictions.map((item) => <div key={`${item.subject}-${item.key}`} className="rounded-lg border border-risk-high/20 bg-risk-high/5 p-3 text-[10px] leading-5 text-risk-high"><span className="mono mr-2 text-[8px] uppercase">Contradiction</span>{item.explanation}</div>)}{data.missingEvidence.map((item) => <div key={item} className="rounded-lg border border-risk-medium/20 bg-risk-medium/5 p-3 text-[10px] leading-5 text-risk-medium"><span className="mono mr-2 text-[8px] uppercase">Evidence gap</span>{item}</div>)}</div>}
    {section === "graph" && <EvidenceGraph data={data}/>}
    {section === "history" && <div><div className="mb-3 grid grid-cols-4 gap-2">{(["dns", "certificate", "http", "technology"] as const).map((category) => <div key={category} className="rounded-lg border border-line bg-base-950/50 p-2 text-center"><div className="text-sm text-ink-soft">{data.history.filter((track) => track.category === category).length}</div><div className="mono text-[8px] uppercase text-ink-faint">{category}</div></div>)}</div><div className="grid gap-2 md:grid-cols-2">{data.history.map((track) => { const changes = track.points.filter((point) => point.changed).length; const latest = track.points.at(-1); return <div key={`${track.category}-${track.subject}-${track.key}`} className="rounded-lg border border-line bg-base-950/55 p-3"><div className="flex justify-between gap-2"><div className="min-w-0"><div className="mono truncate text-[10px] text-ink-soft">{track.subject}</div><div className="mono mt-1 text-[8px] text-ink-faint">{track.key}</div></div><span className={changes ? "text-risk-medium" : "text-signal"}>{changes}Δ</span></div><div className="mt-3 flex gap-1">{track.points.slice(-16).map((point) => <span key={`${point.scanId}-${point.observedAt}`} title={`${point.value} · ${new Date(point.observedAt).toLocaleString()}`} className={`h-2 flex-1 rounded ${point.changed ? "bg-risk-medium" : "bg-signal/30"}`}/>)}</div><div title={latest?.value} className="mt-2 truncate text-[9px] text-ink-faint">Current · {latest?.value}</div></div>; })}</div>{!data.history.length && <div className="rounded-lg border border-dashed border-line p-5 text-xs text-ink-faint">More observations are needed for historical comparison.</div>}</div>}
    {section === "provenance" && <div className="space-y-3"><div className="grid gap-2 md:grid-cols-2">{data.providers.map((provider) => <div key={provider.provider} className="rounded-lg border border-line bg-base-950/50 p-3"><div className="flex justify-between gap-2"><span className="text-xs text-ink-soft">{provider.provider}</span><span className="mono text-[9px] text-signal">{pct(provider.reliability)}</span></div><p className="mt-2 text-[10px] leading-5 text-ink-faint">{provider.explanation}</p></div>)}</div>{data.entityResolution.map((entity) => <div key={entity.entityId} className="rounded-lg border border-line bg-base-950/50 p-3"><div className="mono text-[9px] text-accent">{entity.canonical} · {entity.kind}</div><p className="mt-2 text-[10px] leading-5 text-ink-faint">{entity.explanation}</p><div className="mono mt-2 text-[8px] text-ink-faint">Discovery path · {entity.discoveryPath.join(" → ")}</div></div>)}</div>}
  </div>}</div>}</div>;
}
