"use client";

import { useState } from "react";
import type { GuardianEvidenceIntelligence, GuardianEvidenceRecord } from "@/lib/guardian/types";
import { useTranslator } from "@/lib/i18n/context";
import { localizeAssetKind, localizeDiscoveryMethod } from "@/lib/report/scan-copy";
import type { AssetKind } from "@/lib/types";

const pct = (value: number) => `${Math.round(value * 100)}%`;
const shortHash = (value: string) => `${value.slice(0, 12)}…${value.slice(-8)}`;

function EvidenceGraph({ data }: { data: GuardianEvidenceIntelligence }) {
  const tr = useTranslator();
  const kinds = ["provider", "observation", "entity", "finding"] as const;
  const label = (kind: (typeof kinds)[number], raw: string) => kind === "observation" ? tr.t("guardian", "graphObservation") : kind === "finding" ? tr.t("guardian", "graphFinding") : raw;
  return <div className="overflow-x-auto rounded-xl border border-line bg-base-950/55 p-4"><div className="grid min-w-[680px] grid-cols-4 gap-4">{kinds.map((kind) => <div key={kind}><div className="mono mb-3 text-[11px] uppercase tracking-wider text-ink-faint">{tr.t("guardian", `evidenceKind${kind[0]!.toUpperCase()}${kind.slice(1)}` as Parameters<typeof tr.t<"guardian">>[1])}</div><div className="space-y-2">{data.graph.nodes.filter((node) => node.kind === kind).slice(0, kind === "observation" ? 12 : 8).map((node) => { const copy = label(kind, node.label); return <div key={node.id} title={copy} className={`truncate rounded-lg border p-2 text-[11px] ${kind === "finding" ? "border-signal/30 bg-signal/10 text-signal" : kind === "observation" ? "border-accent/20 bg-accent/5 text-ink-soft" : "border-line bg-base-900 text-ink-faint"}`}><span className="mr-1.5 text-signal">●</span>{copy}<div className="mono mt-1 text-[10px] text-ink-faint">{pct(node.confidence)}</div></div>;})}</div></div>)}</div><div className="mono mt-4 border-t border-line pt-3 text-[11px] text-ink-faint">{tr.t("guardian", "traceableRelationships", { count: data.graph.edges.length })}</div></div>;
}

function ObservationViewer({ records }: { records: GuardianEvidenceRecord[] }) {
  const tr = useTranslator();
  const [selected, setSelected] = useState(records[0]?.id ?? "");
  const [mode, setMode] = useState<"normalized" | "raw">("normalized");
  const record = records.find((item) => item.id === selected) ?? records[0];
  if (!record) return <div className="rounded-lg border border-dashed border-line p-5 text-xs text-ink-faint">{tr.t("guardian", "noMatchingObservations")}</div>;
  const normalized = {
    [tr.t("guardian", "evidenceSubject")]: record.subject,
    [tr.t("guardian", "evidenceKey")]: record.normalized.key,
    [tr.t("guardian", "evidenceValue")]: record.normalized.value,
    [tr.t("guardian", "evidenceProvider")]: record.provider,
    [tr.t("guardian", "evidenceMethod")]: localizeDiscoveryMethod(record.method, tr),
    [tr.t("guardian", "evidenceObservedAt")]: tr.formatDate(record.observedAt, { dateStyle: "medium", timeStyle: "short" }),
    [tr.t("guardian", "discoveryPath")]: record.discoveryPath.map((item) => localizeDiscoveryMethod(item, tr)),
    [tr.t("guardian", "evidenceOrigin")]: tr.t("guardian", record.provenance.origin === "scan_asset" ? "evidenceOriginScanAsset" : record.provenance.origin === "scan_edge" ? "evidenceOriginScanEdge" : "evidenceOriginProviderRun"),
    [tr.t("guardian", "evidenceSourceId")]: record.provenance.sourceId,
    [tr.t("guardian", "evidenceCollectedAt")]: tr.formatDate(record.provenance.collectedAt, { dateStyle: "medium", timeStyle: "short" }),
    [tr.t("guardian", "providerConfidence")]: record.providerConfidence,
    [tr.t("guardian", "evidenceScore")]: record.evidenceScore,
    [tr.t("guardian", "evidenceContentHash")]: record.contentHash,
  };
  return <div className="grid gap-3 lg:grid-cols-[.8fr_1.2fr]"><div className="scroll-thin max-h-72 space-y-1 overflow-y-auto pr-1">{records.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} className={`w-full rounded-lg border p-2.5 text-left ${item.id === record.id ? "border-signal/25 bg-signal/5" : "border-line bg-base-950/50"}`}><div className="flex items-center justify-between gap-2"><span className="mono truncate text-[11px] text-ink-soft">{item.subject}</span><span className="mono text-[10px] text-ink-faint">{Math.round(item.evidenceScore * 100)}</span></div><div className="mt-1 truncate text-[11px] text-ink-faint">{tr.t("guardian", "observationFrom", { provider: item.provider })}</div></button>)}</div><div className="min-w-0 rounded-lg border border-line bg-base-950/70 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex gap-1"><button onClick={() => setMode("normalized")} className={`mono rounded-sm px-2 py-1 text-[10px] uppercase ${mode === "normalized" ? "bg-signal/10 text-signal" : "text-ink-faint"}`}>{tr.t("guardian", "normalized")}</button><button onClick={() => setMode("raw")} className={`mono rounded-sm px-2 py-1 text-[10px] uppercase ${mode === "raw" ? "bg-signal/10 text-signal" : "text-ink-faint"}`}>{tr.t("guardian", "rawObservation")}</button></div><span className="mono text-[10px] text-ink-faint">{tr.t("guardian", `evidenceCategory${record.category[0]!.toUpperCase()}${record.category.slice(1)}` as Parameters<typeof tr.t<"guardian">>[1])} · {tr.t("guardian", `assurance${record.assurance[0]!.toUpperCase()}${record.assurance.slice(1)}` as Parameters<typeof tr.t<"guardian">>[1])}</span></div><pre className="scroll-thin mt-3 max-h-52 overflow-auto whitespace-pre-wrap break-all text-[11px] leading-5 text-ink-soft">{JSON.stringify(mode === "raw" ? record.rawObservation : normalized, null, 2)}</pre></div></div>;
}

export function EvidenceIntelligencePanel({ orgId, target, findingId, agencyId }: { orgId: string; target: string; findingId: string; agencyId?: string }) {
  const tr = useTranslator();
  const [open, setOpen] = useState(false);
  const [data, setData] = useState<GuardianEvidenceIntelligence | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [section, setSection] = useState<"evidence" | "graph" | "history" | "provenance">("evidence");
  const toggle = async () => {
    setOpen((value) => !value);
    if (data || loading || open) return;
    setLoading(true); setError("");
    const response = await fetch(`/api/guardian/evidence?orgId=${encodeURIComponent(orgId)}&target=${encodeURIComponent(target)}&findingId=${encodeURIComponent(findingId)}${agencyId ? `&agencyId=${encodeURIComponent(agencyId)}` : ""}`, { cache: "no-store" });
    if (response.ok) setData(await response.json() as GuardianEvidenceIntelligence);
    else setError(tr.t("guardian", response.status === 404 ? "evidenceSnapshotUnavailable" : "evidenceLoadFailed"));
    setLoading(false);
  };
  return <div className="mt-4 border-t border-line pt-4"><button onClick={() => void toggle()} className="mono flex w-full items-center justify-between text-[11px] uppercase tracking-wider text-accent"><span>{tr.t("guardian", "evidenceIntelligence")}</span><span>{tr.t("guardian", open ? "closeEvidence" : "explainFinding")}</span></button>{open && <div className="mt-4">{loading && <div className="animate-pulse rounded-lg border border-line p-5 text-xs text-ink-faint">{tr.t("guardian", "correlatingObservations")}</div>}{error && <div className="rounded-lg border border-risk-medium/20 bg-risk-medium/5 p-4 text-xs text-risk-medium">{error}</div>}{data && <div className="space-y-4">
    <section className="rounded-xl border border-signal/20 bg-signal/4 p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><div className="mono text-[11px] uppercase tracking-[.16em] text-signal">{tr.t("guardian", "whyWeBelieve")}</div><p className="mt-2 text-xs leading-5 text-ink-soft">{tr.t("guardian", "whyWeBelieveBody", { count: data.supportingEvidence.length })}</p><p className="mt-2 text-[11px] leading-5 text-ink-faint">{tr.t("guardian", "confidenceBody")}</p></div><div className="grid grid-cols-2 gap-2 text-center"><div className="rounded-lg bg-base-950/70 px-3 py-2"><div className="text-lg text-signal">{pct(data.confidence)}</div><div className="mono text-[10px] uppercase text-ink-faint">{tr.t("guardian", "confidence")}</div></div><div className="rounded-lg bg-base-950/70 px-3 py-2"><div className="text-lg text-accent">{data.evidenceScore}</div><div className="mono text-[10px] uppercase text-ink-faint">{tr.t("guardian", "evidenceScore")}</div></div></div></div><div className="mono mt-3 border-t border-signal/10 pt-3 text-[10px] text-ink-faint">{tr.t("guardian", "immutableSnapshot")} · {data.snapshot.scanId} · SHA-256 {shortHash(data.snapshot.contentHash)}</div></section>
    <div className="flex flex-wrap gap-1">{(["evidence", "graph", "history", "provenance"] as const).map((item) => <button key={item} onClick={() => setSection(item)} className={`mono rounded-full border px-2.5 py-1 text-[10px] uppercase ${section === item ? "border-signal/30 bg-signal/10 text-signal" : "border-line text-ink-faint"}`}>{tr.t("guardian", `evidenceTab${item[0]!.toUpperCase()}${item.slice(1)}` as Parameters<typeof tr.t<"guardian">>[1])}</button>)}</div>
    {section === "evidence" && <div className="space-y-3"><ObservationViewer records={data.supportingEvidence}/>{data.correlations.map((item, index) => <div key={item} className="rounded-lg border border-accent/15 bg-accent/5 p-3 text-[11px] leading-5 text-ink-soft"><span className="mono mr-2 text-[10px] uppercase text-accent">{tr.t("guardian", "correlation")}</span>{tr.t("guardian", "correlationBody", { count: index + 1 })}</div>)}{data.contradictions.map((item) => <div key={`${item.subject}-${item.key}`} className="rounded-lg border border-risk-high/20 bg-risk-high/5 p-3 text-[11px] leading-5 text-risk-high"><span className="mono mr-2 text-[10px] uppercase">{tr.t("guardian", "contradiction")}</span>{tr.t("guardian", "contradictionBody", { subject: item.subject })}</div>)}{data.missingEvidence.map((item) => <div key={item} className="rounded-lg border border-risk-medium/20 bg-risk-medium/5 p-3 text-[11px] leading-5 text-risk-medium"><span className="mono mr-2 text-[10px] uppercase">{tr.t("guardian", "evidenceGap")}</span>{tr.t("guardian", "evidenceGapBody")}</div>)}</div>}
    {section === "graph" && <EvidenceGraph data={data}/>}
    {section === "history" && <div><div className="mb-3 grid grid-cols-4 gap-2">{(["dns", "certificate", "http", "technology"] as const).map((category) => <div key={category} className="rounded-lg border border-line bg-base-950/50 p-2 text-center"><div className="text-sm text-ink-soft">{data.history.filter((track) => track.category === category).length}</div><div className="mono text-[10px] uppercase text-ink-faint">{tr.t("guardian", `evidenceCategory${category[0]!.toUpperCase()}${category.slice(1)}` as Parameters<typeof tr.t<"guardian">>[1])}</div></div>)}</div><div className="grid gap-2 md:grid-cols-2">{data.history.map((track) => { const changes = track.points.filter((point) => point.changed).length; const latest = track.points.at(-1); return <div key={`${track.category}-${track.subject}-${track.key}`} className="rounded-lg border border-line bg-base-950/55 p-3"><div className="flex justify-between gap-2"><div className="min-w-0"><div className="mono truncate text-[11px] text-ink-soft">{track.subject}</div><div className="mono mt-1 text-[10px] text-ink-faint">{track.key}</div></div><span className={changes ? "text-risk-medium" : "text-signal"}>{changes}Δ</span></div><div className="mt-3 flex gap-1">{track.points.slice(-16).map((point) => <span key={`${point.scanId}-${point.observedAt}`} title={`${point.value} · ${tr.formatDate(point.observedAt, { dateStyle: "medium", timeStyle: "short" })}`} className={`h-2 flex-1 rounded-sm ${point.changed ? "bg-risk-medium" : "bg-signal/30"}`}/>)}</div><div title={latest?.value} className="mt-2 truncate text-[11px] text-ink-faint">{tr.t("guardian", "current")} · {latest?.value}</div></div>; })}</div>{!data.history.length && <div className="rounded-lg border border-dashed border-line p-5 text-xs text-ink-faint">{tr.t("guardian", "historyNeedsObservations")}</div>}</div>}
    {section === "provenance" && <div className="space-y-3"><div className="grid gap-2 md:grid-cols-2">{data.providers.map((provider) => <div key={provider.provider} className="rounded-lg border border-line bg-base-950/50 p-3"><div className="flex justify-between gap-2"><span className="text-xs text-ink-soft">{provider.provider}</span><span className="mono text-[11px] text-signal">{pct(provider.reliability)}</span></div><p className="mt-2 text-[11px] leading-5 text-ink-faint">{tr.t("guardian", "providerEvidenceBody", { count: provider.observations })}</p></div>)}</div>{data.entityResolution.map((entity) => <div key={entity.entityId} className="rounded-lg border border-line bg-base-950/50 p-3"><div className="mono text-[11px] text-accent">{entity.canonical} · {localizeAssetKind(entity.kind as AssetKind, tr)}</div><p className="mt-2 text-[11px] leading-5 text-ink-faint">{tr.t("guardian", "entityResolutionBody", { confidence: Math.round(entity.confidence * 100) })}</p><div className="mono mt-2 text-[10px] text-ink-faint">{tr.t("guardian", "discoveryPath")} · {entity.discoveryPath.map((item) => localizeDiscoveryMethod(item, tr)).join(" → ")}</div></div>)}</div>}
  </div>}</div>}</div>;
}
